local ffi = require "ffi"
ffi.cdef [[
typedef uint32_t volatile uatomic_uint32_t;
typedef void (*urefcount_cb)(struct urefcount *);
struct urefcount {
	uatomic_uint32_t refcount;
	urefcount_cb cb;
};
typedef long int __time_t;
typedef __time_t time_t;
struct uclock {
	struct urefcount *refcount;
	uint64_t (*uclock_now)(struct uclock *);
	time_t (*uclock_mktime)(struct uclock *, uint64_t);
};
enum uclock_std_flags {
	UCLOCK_FLAG_REALTIME = 1,
};
struct uclock *uclock_std_alloc(enum uclock_std_flags);
struct umem {
	struct umem_mgr *mgr;
	uint8_t *buffer;
	size_t size;
	size_t real_size;
};
struct umem_mgr {
	struct urefcount *refcount;
	bool (*umem_alloc)(struct umem_mgr *, struct umem *, size_t);
	bool (*umem_realloc)(struct umem *, size_t);
	void (*umem_free)(struct umem *);
	void (*umem_mgr_vacuum)(struct umem_mgr *);
};
struct umem_mgr *umem_alloc_mgr_alloc(void);
struct umem_mgr *umem_pool_mgr_alloc(size_t, size_t, ...);
struct umem_mgr *umem_pool_mgr_alloc_simple(uint16_t);
struct uchain {
	struct uchain *next;
	struct uchain *prev;
};
struct ubuf {
	struct uchain uchain;
	struct ubuf_mgr *mgr;
};
struct ubuf_mgr {
	struct urefcount *refcount;
	uint32_t signature;
	struct ubuf *(*ubuf_alloc)(struct ubuf_mgr *, uint32_t, va_list);
	int (*ubuf_control)(struct ubuf *, int, va_list);
	void (*ubuf_free)(struct ubuf *);
	int (*ubuf_mgr_control)(struct ubuf_mgr *, int, va_list);
};
struct ubuf_mgr *ubuf_block_mem_mgr_alloc(uint16_t, uint16_t, struct umem_mgr *, int, int);
struct udict {
	struct udict_mgr *mgr;
};
struct udict_mgr {
	struct urefcount *refcount;
	struct udict *(*udict_alloc)(struct udict_mgr *, size_t);
	int (*udict_control)(struct udict *, int, va_list);
	void (*udict_free)(struct udict *);
	int (*udict_mgr_control)(struct udict_mgr *, int, va_list);
};
struct uref_mgr {
	struct urefcount *refcount;
	size_t control_attr_size;
	struct udict_mgr *udict_mgr;
	struct uref *(*uref_alloc)(struct uref_mgr *);
	void (*uref_free)(struct uref *);
	int (*uref_mgr_control)(struct uref_mgr *, int, va_list);
};
struct uref {
	struct uchain uchain;
	struct uref_mgr *mgr;
	struct ubuf *ubuf;
	struct udict *udict;
	uint64_t flags;
	uint64_t date_sys;
	uint64_t date_prog;
	uint64_t date_orig;
	uint64_t dts_pts_delay;
	uint64_t cr_dts_delay;
	uint64_t rap_cr_delay;
	uint64_t priv;
};
struct ubuf_mgr *ubuf_mem_mgr_alloc_from_flow_def(uint16_t, uint16_t, struct umem_mgr *, struct uref *);
typedef uint16_t uring_index;
struct uring_elem {
	uint16_t tag;
	uring_index next;
	void *opaque;
};
struct uring {
	uint16_t length;
	struct uring_elem *elems;
};
typedef uatomic_uint32_t uring_lifo;
struct ulifo {
	struct uring uring;
	uring_lifo lifo_carrier;
	uring_lifo lifo_empty;
};
typedef void *(*upool_alloc_cb)(struct upool *);
typedef void (*upool_free_cb)(struct upool *, void *);
struct upool {
	struct ulifo lifo;
	upool_alloc_cb alloc_cb;
	upool_free_cb free_cb;
};
void *ubuf_mem_shared_alloc_inner(struct upool *);
void ubuf_mem_shared_free_inner(struct upool *, void *);
int ubuf_pic_common_check_size(struct ubuf_mgr *, int, int);
int ubuf_pic_common_dup(struct ubuf *, struct ubuf *);
int ubuf_pic_common_plane_dup(struct ubuf *, struct ubuf *, uint8_t);
int ubuf_pic_common_size(struct ubuf *, size_t *, size_t *, uint8_t *);
int ubuf_pic_common_plane_iterate(struct ubuf *, char const **);
int ubuf_pic_common_plane_size(struct ubuf *, char const *, size_t *, uint8_t *, uint8_t *, uint8_t *);
int ubuf_pic_common_plane_map(struct ubuf *, char const *, int, int, int, int, uint8_t **);
int ubuf_pic_common_check_skip(struct ubuf_mgr *, int, int);
int ubuf_pic_common_resize(struct ubuf *, int, int, int, int);
void ubuf_pic_common_mgr_clean(struct ubuf_mgr *);
void ubuf_pic_common_mgr_init(struct ubuf_mgr *, uint8_t);
int ubuf_pic_common_mgr_add_plane(struct ubuf_mgr *, char const *, uint8_t, uint8_t, uint8_t);
int ubuf_pic_plane_clear(struct ubuf *, char const *, int, int, int, int);
int ubuf_pic_clear(struct ubuf *, int, int, int, int);
struct ubuf_mgr *ubuf_pic_mem_mgr_alloc(uint16_t, uint16_t, struct umem_mgr *, uint8_t, int, int, int, int, int, int);
int ubuf_pic_mem_mgr_add_plane(struct ubuf_mgr *, char const *, uint8_t, uint8_t, uint8_t);
struct ubuf_mgr *ubuf_pic_mem_mgr_alloc_fourcc(uint16_t, uint16_t, struct umem_mgr *, char const *, int, int, int, int, int, int);
int ubuf_sound_common_dup(struct ubuf *, struct ubuf *);
int ubuf_sound_common_plane_dup(struct ubuf *, struct ubuf *, uint8_t);
int ubuf_sound_common_size(struct ubuf *, size_t *, uint8_t *);
int ubuf_sound_common_plane_iterate(struct ubuf *, char const **);
int ubuf_sound_common_plane_map(struct ubuf *, char const *, int, int, uint8_t **);
int ubuf_sound_common_resize(struct ubuf *, int, int);
void ubuf_sound_common_mgr_clean(struct ubuf_mgr *);
void ubuf_sound_common_mgr_init(struct ubuf_mgr *, uint8_t);
int ubuf_sound_common_mgr_add_plane(struct ubuf_mgr *, char const *);
struct ubuf_mgr *ubuf_sound_mem_mgr_alloc(uint16_t, uint16_t, struct umem_mgr *, uint8_t, uint64_t);
int ubuf_sound_mem_mgr_add_plane(struct ubuf_mgr *, char const *);
struct udict_mgr *udict_inline_mgr_alloc(unsigned int, struct umem_mgr *, int, int);
struct uref_mgr *uref_std_mgr_alloc(uint16_t, struct udict_mgr *, int);
struct upump;
struct upipe_mgr {
	struct urefcount *refcount;
	unsigned int signature;
	char const *(*upipe_err_str)(int);
	char const *(*upipe_command_str)(int);
	char const *(*upipe_event_str)(int);
	struct upipe *(*upipe_alloc)(struct upipe_mgr *, struct uprobe *, uint32_t, va_list);
	void (*upipe_input)(struct upipe *, struct uref *, struct upump **);
	int (*upipe_control)(struct upipe *, int, va_list);
	int (*upipe_mgr_control)(struct upipe_mgr *, int, va_list);
};
struct upipe {
	struct urefcount *refcount;
	struct uchain uchain;
	void *opaque;
	struct uprobe *uprobe;
	struct upipe_mgr *mgr;
};
typedef int (*uprobe_throw_func)(struct uprobe *, struct upipe *, int, va_list);
struct uprobe {
	struct urefcount *refcount;
	uprobe_throw_func uprobe_throw;
	struct uprobe *next;
};
void uprobe_dejitter_set(struct uprobe *, unsigned int);
struct uprobe_dejitter {
	unsigned int divider;
	unsigned int offset_count;
	int64_t offset;
	int64_t offset_residue;
	unsigned int deviation_count;
	uint64_t deviation;
	uint64_t deviation_residue;
	struct uprobe uprobe;
};
struct uprobe *uprobe_dejitter_init(struct uprobe_dejitter *, struct uprobe *, unsigned int);
void uprobe_dejitter_clean(struct uprobe_dejitter *);
struct uprobe *uprobe_dejitter_alloc(struct uprobe *, unsigned int);
enum uprobe_log_level {
	UPROBE_LOG_VERBOSE,
	UPROBE_LOG_DEBUG,
	UPROBE_LOG_NOTICE,
	UPROBE_LOG_WARNING,
	UPROBE_LOG_ERROR,
};
struct uprobe_pfx {
	char *name;
	enum uprobe_log_level min_level;
	struct uprobe uprobe;
};
struct uprobe *uprobe_pfx_init(struct uprobe_pfx *, struct uprobe *, enum uprobe_log_level, char const *);
void uprobe_pfx_clean(struct uprobe_pfx *);
struct uprobe *uprobe_pfx_alloc(struct uprobe *, enum uprobe_log_level, char const *);
struct uprobe *uprobe_pfx_alloc_va(struct uprobe *, enum uprobe_log_level, char const *, ...);
struct uprobe_output {
	struct uprobe uprobe;
};
struct uprobe *uprobe_output_init(struct uprobe_output *, struct uprobe *);
void uprobe_output_clean(struct uprobe_output *);
struct uprobe *uprobe_output_alloc(struct uprobe *);
enum uprobe_selflow_type {
	UPROBE_SELFLOW_VOID,
	UPROBE_SELFLOW_PIC,
	UPROBE_SELFLOW_SOUND,
	UPROBE_SELFLOW_SUBPIC,
};
struct uprobe *uprobe_selflow_alloc(struct uprobe *, struct uprobe *, enum uprobe_selflow_type, char const *);
void uprobe_selflow_get(struct uprobe *, char const **);
int uprobe_selflow_set(struct uprobe *, char const *);
int uprobe_selflow_set_va(struct uprobe *, char const *, ...);
typedef struct FILE FILE;
struct uprobe_stdio {
	FILE *stream;
	enum uprobe_log_level min_level;
	struct uprobe uprobe;
};
struct uprobe *uprobe_stdio_init(struct uprobe_stdio *, struct uprobe *, FILE *, enum uprobe_log_level);
void uprobe_stdio_clean(struct uprobe_stdio *);
struct uprobe *uprobe_stdio_alloc(struct uprobe *, FILE *, enum uprobe_log_level);
struct uprobe_stdio_color {
	FILE *stream;
	enum uprobe_log_level min_level;
	struct uprobe uprobe;
};
struct uprobe *uprobe_stdio_color_init(struct uprobe_stdio_color *, struct uprobe *, FILE *, enum uprobe_log_level);
void uprobe_stdio_color_clean(struct uprobe_stdio_color *);
struct uprobe *uprobe_stdio_color_alloc(struct uprobe *, FILE *, enum uprobe_log_level);
struct uprobe_syslog {
	char *ident;
	enum uprobe_log_level min_level;
	struct uprobe uprobe;
};
struct uprobe *uprobe_syslog_init(struct uprobe_syslog *, struct uprobe *, char *, int, int, enum uprobe_log_level);
void uprobe_syslog_clean(struct uprobe_syslog *);
struct uprobe *uprobe_syslog_alloc(struct uprobe *, char *, int, int, enum uprobe_log_level);
struct uprobe_xfer {
	struct uchain subs;
	struct uprobe uprobe;
};
struct uprobe *uprobe_xfer_init(struct uprobe_xfer *, struct uprobe *);
void uprobe_xfer_clean(struct uprobe_xfer *);
struct uprobe *uprobe_xfer_alloc(struct uprobe *);
enum uprobe_xfer_event {
	UPROBE_XFER_SENTINEL = 65536,
	UPROBE_XFER_VOID,
	UPROBE_XFER_UINT64_T,
	UPROBE_XFER_UNSIGNED_LONG_LOCAL,
};
int uprobe_xfer_add(struct uprobe *, enum uprobe_xfer_event, int, uint32_t);
struct uprobe_ubuf_mem {
	struct umem_mgr *umem_mgr;
	uint16_t ubuf_pool_depth;
	uint16_t shared_pool_depth;
	struct uprobe uprobe;
};
struct uprobe *uprobe_ubuf_mem_init(struct uprobe_ubuf_mem *, struct uprobe *, struct umem_mgr *, uint16_t, uint16_t);
void uprobe_ubuf_mem_clean(struct uprobe_ubuf_mem *);
struct uprobe *uprobe_ubuf_mem_alloc(struct uprobe *, struct umem_mgr *, uint16_t, uint16_t);
void uprobe_ubuf_mem_set(struct uprobe *, struct umem_mgr *);
typedef void *volatile uatomic_ptr_t;
struct uprobe_ubuf_mem_pool {
	struct umem_mgr *umem_mgr;
	uint16_t ubuf_pool_depth;
	uint16_t shared_pool_depth;
	uatomic_ptr_t first;
	struct uprobe uprobe;
};
struct uprobe *uprobe_ubuf_mem_pool_init(struct uprobe_ubuf_mem_pool *, struct uprobe *, struct umem_mgr *, uint16_t, uint16_t);
void uprobe_ubuf_mem_pool_vacuum(struct uprobe_ubuf_mem_pool *);
void uprobe_ubuf_mem_pool_clean(struct uprobe_ubuf_mem_pool *);
struct uprobe *uprobe_ubuf_mem_pool_alloc(struct uprobe *, struct umem_mgr *, uint16_t, uint16_t);
void uprobe_ubuf_mem_pool_set(struct uprobe *, struct umem_mgr *);
struct uprobe_uclock {
	struct uclock *uclock;
	struct uprobe uprobe;
};
struct uprobe *uprobe_uclock_init(struct uprobe_uclock *, struct uprobe *, struct uclock *);
void uprobe_uclock_clean(struct uprobe_uclock *);
struct uprobe *uprobe_uclock_alloc(struct uprobe *, struct uclock *);
void uprobe_uclock_set(struct uprobe *, struct uclock *);
enum upump_type {
	UPUMP_TYPE_IDLER,
	UPUMP_TYPE_TIMER,
	UPUMP_TYPE_FD_READ,
	UPUMP_TYPE_FD_WRITE,
};
struct upump_blocker;
struct upump_mgr {
	struct urefcount *refcount;
	struct uchain uchain;
	void *opaque;
	struct upump *(*upump_alloc)(struct upump_mgr *, enum upump_type, va_list);
	void (*upump_start)(struct upump *);
	void (*upump_stop)(struct upump *);
	void (*upump_free)(struct upump *);
	struct upump_blocker *(*upump_blocker_alloc)(struct upump *);
	void (*upump_blocker_free)(struct upump_blocker *);
	int (*upump_mgr_control)(struct upump_mgr *, int, va_list);
};
struct uprobe_upump_mgr {
	struct upump_mgr *upump_mgr;
	bool frozen;
	struct uprobe uprobe;
};
struct uprobe *uprobe_upump_mgr_init(struct uprobe_upump_mgr *, struct uprobe *, struct upump_mgr *);
void uprobe_upump_mgr_clean(struct uprobe_upump_mgr *);
struct uprobe *uprobe_upump_mgr_alloc(struct uprobe *, struct upump_mgr *);
void uprobe_upump_mgr_set(struct uprobe *, struct upump_mgr *);
struct uprobe_uref_mgr {
	struct uref_mgr *uref_mgr;
	struct uprobe uprobe;
};
struct uprobe *uprobe_uref_mgr_init(struct uprobe_uref_mgr *, struct uprobe *, struct uref_mgr *);
void uprobe_uref_mgr_clean(struct uprobe_uref_mgr *);
struct uprobe *uprobe_uref_mgr_alloc(struct uprobe *, struct uref_mgr *);
void uprobe_uref_mgr_set(struct uprobe *, struct uref_mgr *);
struct upump_blocker *upump_common_blocker_alloc(struct upump *);
void upump_common_blocker_free(struct upump_blocker *);
void upump_common_blocker_free_inner(struct upool *, void *);
void upump_common_init(struct upump *);
void upump_common_dispatch(struct upump *);
void upump_common_start(struct upump *);
void upump_common_stop(struct upump *);
void upump_common_clean(struct upump *);
size_t upump_common_mgr_sizeof(uint16_t, uint16_t);
void upump_common_mgr_vacuum(struct upump_mgr *);
void upump_common_mgr_clean(struct upump_mgr *);
void upump_common_mgr_init(struct upump_mgr *, uint16_t, uint16_t, void *, void (*)(struct upump *), void (*)(struct upump *), void *(*)(struct upool *), void (*)(struct upool *, void *));
void urefcount_release(struct urefcount *);
bool urefcount_single(struct urefcount *);
bool urefcount_dead(struct urefcount *);
int ubuf_block_check_size(struct ubuf *, int *, int *);
enum udict_type {
	UDICT_TYPE_END,
	UDICT_TYPE_OPAQUE,
	UDICT_TYPE_STRING,
	UDICT_TYPE_VOID,
	UDICT_TYPE_BOOL,
	UDICT_TYPE_SMALL_UNSIGNED,
	UDICT_TYPE_SMALL_INT,
	UDICT_TYPE_UNSIGNED,
	UDICT_TYPE_INT,
	UDICT_TYPE_RATIONAL,
	UDICT_TYPE_FLOAT,
	UDICT_TYPE_SHORTHAND = 16,
	UDICT_TYPE_FLOW_RANDOM,
	UDICT_TYPE_FLOW_ERROR,
	UDICT_TYPE_FLOW_DEF,
	UDICT_TYPE_FLOW_ID,
	UDICT_TYPE_FLOW_RAWDEF,
	UDICT_TYPE_FLOW_LANGUAGES,
	UDICT_TYPE_EVENT_EVENTS,
	UDICT_TYPE_CLOCK_DURATION,
	UDICT_TYPE_CLOCK_LATENCY,
	UDICT_TYPE_BLOCK_END,
	UDICT_TYPE_PIC_NUM,
	UDICT_TYPE_PIC_KEY,
	UDICT_TYPE_PIC_HSIZE,
	UDICT_TYPE_PIC_VSIZE,
	UDICT_TYPE_PIC_HSIZE_VISIBLE,
	UDICT_TYPE_PIC_VSIZE_VISIBLE,
	UDICT_TYPE_PIC_VIDEO_FORMAT,
	UDICT_TYPE_PIC_FULL_RANGE,
	UDICT_TYPE_PIC_COLOUR_PRIMARIES,
	UDICT_TYPE_PIC_TRANSFER_CHARACTERISTICS,
	UDICT_TYPE_PIC_MATRIX_COEFFICIENTS,
	UDICT_TYPE_PIC_HPOSITION,
	UDICT_TYPE_PIC_VPOSITION,
	UDICT_TYPE_PIC_SAR,
	UDICT_TYPE_PIC_OVERSCAN,
	UDICT_TYPE_PIC_PROGRESSIVE,
	UDICT_TYPE_PIC_TF,
	UDICT_TYPE_PIC_BF,
	UDICT_TYPE_PIC_TFF,
};
int udict_get_string(struct udict *, char const **, enum udict_type, char const *);
int udict_get_bool(struct udict *, bool *, enum udict_type, char const *);
int udict_get_small_unsigned(struct udict *, uint8_t *, enum udict_type, char const *);
int udict_get_small_int(struct udict *, int8_t *, enum udict_type, char const *);
int64_t udict_get_int64(uint8_t const *);
int udict_get_unsigned(struct udict *, uint64_t *, enum udict_type, char const *);
int udict_get_int(struct udict *, int64_t *, enum udict_type, char const *);
int udict_get_float(struct udict *, double *, enum udict_type, char const *);
struct urational {
	int64_t num;
	uint64_t den;
};
int udict_get_rational(struct udict *, struct urational *, enum udict_type, char const *);
void udict_set_int64(uint8_t *, int64_t);
typedef int (*urequest_func)(struct urequest *, va_list);
typedef void (*urequest_free_func)(struct urequest *);
struct urequest {
	struct uchain uchain;
	void *opaque;
	int type;
	struct uref *uref;
	urequest_func urequest_provide;
	urequest_free_func urequest_free;
};
void urequest_init(struct urequest *, int, struct uref *, urequest_func, urequest_free_func);
int upipe_control_nodbg_va(struct upipe *, int, va_list);
char const *ubase_err_str(int);
bool ubase_check(int);
uint64_t ubase_gcd(uint64_t, uint64_t);
int ubase_ncmp(char const *, char const *);
void urefcount_init(struct urefcount *, urefcount_cb);
void urefcount_reset(struct urefcount *);
struct urefcount *urefcount_use(struct urefcount *);
void urefcount_clean(struct urefcount *);
struct ubuf *ubuf_alloc(struct ubuf_mgr *, uint32_t, ...);
int ubuf_control_va(struct ubuf *, int, va_list);
int ubuf_control(struct ubuf *, int, ...);
struct ubuf *ubuf_dup(struct ubuf *);
void ubuf_free(struct ubuf *);
struct ubuf_mgr *ubuf_mgr_use(struct ubuf_mgr *);
void ubuf_mgr_release(struct ubuf_mgr *);
int ubuf_mgr_control_va(struct ubuf_mgr *, int, va_list);
int ubuf_mgr_control(struct ubuf_mgr *, int, ...);
int ubuf_mgr_check(struct ubuf_mgr *, struct uref *);
int ubuf_mgr_vacuum(struct ubuf_mgr *);
struct ubuf *ubuf_block_alloc(struct ubuf_mgr *, int);
int ubuf_block_size(struct ubuf *, size_t *);
struct ubuf *ubuf_block_get(struct ubuf *, int *, int *);
int ubuf_block_size_linear(struct ubuf *, int, size_t *);
int ubuf_block_read(struct ubuf *, int, int *, uint8_t const **);
int ubuf_block_write(struct ubuf *, int, int *, uint8_t **);
int ubuf_block_unmap(struct ubuf *, int);
int ubuf_block_append(struct ubuf *, struct ubuf *);
int ubuf_block_split(struct ubuf *, int);
int ubuf_block_insert(struct ubuf *, int, struct ubuf *);
int ubuf_block_delete(struct ubuf *, int, int);
int ubuf_block_truncate(struct ubuf *, int);
int ubuf_block_resize(struct ubuf *, int, int);
struct ubuf *ubuf_block_splice(struct ubuf *, int, int);
uint8_t const *ubuf_block_peek(struct ubuf *, int, int, uint8_t *);
int ubuf_block_peek_unmap(struct ubuf *, int, uint8_t *, uint8_t const *);
int ubuf_block_extract(struct ubuf *, int, int, uint8_t *);
int ubuf_block_iovec_count(struct ubuf *, int, int);
int ubuf_block_iovec_read(struct ubuf *, int, int, struct iovec *);
int ubuf_block_iovec_unmap(struct ubuf *, int, int, struct iovec *);
bool ubuf_block_check_resize(struct ubuf *, int *, int *, size_t *);
struct ubuf *ubuf_block_copy(struct ubuf_mgr *, struct ubuf *, int, int);
int ubuf_block_merge(struct ubuf_mgr *, struct ubuf **, int, int);
int ubuf_block_compare(struct ubuf *, int, struct ubuf *);
int ubuf_block_equal(struct ubuf *, struct ubuf *);
int ubuf_block_match(struct ubuf *, uint8_t const *, uint8_t const *, size_t);
int ubuf_block_scan(struct ubuf *, size_t *, uint8_t);
int ubuf_block_find_va(struct ubuf *, size_t *, unsigned int, va_list);
int ubuf_block_find(struct ubuf *, size_t *, unsigned int, ...);
void ubuf_block_common_init(struct ubuf *, bool);
void ubuf_block_common_set(struct ubuf *, size_t, size_t);
void ubuf_block_common_set_buffer(struct ubuf *, uint8_t *);
int ubuf_block_common_dup(struct ubuf *, struct ubuf *);
int ubuf_block_common_splice(struct ubuf *, struct ubuf *, int, int);
void ubuf_block_common_clean(struct ubuf *);
struct ubuf_block_stream {
	struct ubuf *ubuf;
	uint8_t const *buffer;
	uint8_t const *end;
	int offset;
	int size;
	uint32_t bits;
	uint32_t available;
	bool overflow;
};
int ubuf_block_stream_init(struct ubuf_block_stream *, struct ubuf *, int);
int ubuf_block_stream_clean(struct ubuf_block_stream *);
int ubuf_block_stream_get(struct ubuf_block_stream *, uint8_t *);
uint8_t *umem_buffer(struct umem *);
size_t umem_size(struct umem *);
bool umem_alloc(struct umem_mgr *, struct umem *, size_t);
bool umem_realloc(struct umem *, size_t);
void umem_free(struct umem *);
void umem_mgr_vacuum(struct umem_mgr *);
struct umem_mgr *umem_mgr_use(struct umem_mgr *);
void umem_mgr_release(struct umem_mgr *);
struct ubuf_mem_shared {
	uatomic_uint32_t refcount;
	struct umem umem;
};
struct ubuf_mem_shared *ubuf_mem_shared_use(struct ubuf_mem_shared *);
bool ubuf_mem_shared_release(struct ubuf_mem_shared *);
bool ubuf_mem_shared_single(struct ubuf_mem_shared *);
uint8_t *ubuf_mem_shared_buffer(struct ubuf_mem_shared *);
size_t ubuf_mem_shared_size(struct ubuf_mem_shared *);
int ubuf_pic_common_plane(struct ubuf_mgr *, char const *);
size_t ubuf_pic_common_sizeof(struct ubuf_mgr *);
void ubuf_pic_common_init(struct ubuf *, size_t, size_t, size_t, size_t, size_t, size_t);
void ubuf_pic_common_clean(struct ubuf *);
void ubuf_pic_common_plane_init(struct ubuf *, uint8_t, uint8_t *, size_t);
void ubuf_pic_common_plane_clean(struct ubuf *, uint8_t);
struct ubuf *ubuf_pic_alloc(struct ubuf_mgr *, int, int);
int ubuf_pic_size(struct ubuf *, size_t *, size_t *, uint8_t *);
int ubuf_pic_plane_iterate(struct ubuf *, char const **);
int ubuf_pic_plane_size(struct ubuf *, char const *, size_t *, uint8_t *, uint8_t *, uint8_t *);
int ubuf_pic_plane_check_offset(struct ubuf *, char const *, int *, int *, int *, int *);
int ubuf_pic_plane_read(struct ubuf *, char const *, int, int, int, int, uint8_t const **);
int ubuf_pic_plane_write(struct ubuf *, char const *, int, int, int, int, uint8_t **);
int ubuf_pic_plane_unmap(struct ubuf *, char const *, int, int, int, int);
int ubuf_pic_check_resize(struct ubuf *, int *, int *, int *, int *, size_t *, size_t *, uint8_t *);
int ubuf_pic_resize(struct ubuf *, int, int, int, int);
struct ubuf *ubuf_pic_copy(struct ubuf_mgr *, struct ubuf *, int, int, int, int);
int ubuf_pic_replace(struct ubuf_mgr *, struct ubuf **, int, int, int, int);
int ubuf_sound_common_plane(struct ubuf_mgr *, char const *);
size_t ubuf_sound_common_sizeof(struct ubuf_mgr *);
void ubuf_sound_common_init(struct ubuf *, size_t);
void ubuf_sound_common_clean(struct ubuf *);
void ubuf_sound_common_plane_init(struct ubuf *, uint8_t, uint8_t *);
void ubuf_sound_common_plane_clean(struct ubuf *, uint8_t);
struct ubuf *ubuf_sound_alloc(struct ubuf_mgr *, int);
int ubuf_sound_size(struct ubuf *, size_t *, uint8_t *);
int ubuf_sound_plane_iterate(struct ubuf *, char const **);
int ubuf_sound_plane_unmap(struct ubuf *, char const *, int, int);
int ubuf_sound_unmap(struct ubuf *, int, int, uint8_t);
int ubuf_sound_plane_read_void(struct ubuf *, char const *, int, int, void const **);
int ubuf_sound_plane_write_void(struct ubuf *, char const *, int, int, void **);
int ubuf_sound_read_void(struct ubuf *, int, int, void const **, uint8_t);
int ubuf_sound_write_void(struct ubuf *, int, int, void **, uint8_t);
int ubuf_sound_plane_read_uint8_t(struct ubuf *, char const *, int, int, uint8_t const **);
int ubuf_sound_plane_write_uint8_t(struct ubuf *, char const *, int, int, uint8_t **);
int ubuf_sound_read_uint8_t(struct ubuf *, int, int, uint8_t const **, uint8_t);
int ubuf_sound_write_uint8_t(struct ubuf *, int, int, uint8_t **, uint8_t);
int ubuf_sound_plane_read_int16_t(struct ubuf *, char const *, int, int, int16_t const **);
int ubuf_sound_plane_write_int16_t(struct ubuf *, char const *, int, int, int16_t **);
int ubuf_sound_read_int16_t(struct ubuf *, int, int, int16_t const **, uint8_t);
int ubuf_sound_write_int16_t(struct ubuf *, int, int, int16_t **, uint8_t);
int ubuf_sound_plane_read_int32_t(struct ubuf *, char const *, int, int, int32_t const **);
int ubuf_sound_plane_write_int32_t(struct ubuf *, char const *, int, int, int32_t **);
int ubuf_sound_read_int32_t(struct ubuf *, int, int, int32_t const **, uint8_t);
int ubuf_sound_write_int32_t(struct ubuf *, int, int, int32_t **, uint8_t);
int ubuf_sound_plane_read_float(struct ubuf *, char const *, int, int, float const **);
int ubuf_sound_plane_write_float(struct ubuf *, char const *, int, int, float **);
int ubuf_sound_read_float(struct ubuf *, int, int, float const **, uint8_t);
int ubuf_sound_write_float(struct ubuf *, int, int, float **, uint8_t);
int ubuf_sound_plane_read_double(struct ubuf *, char const *, int, int, double const **);
int ubuf_sound_plane_write_double(struct ubuf *, char const *, int, int, double **);
int ubuf_sound_read_double(struct ubuf *, int, int, double const **, uint8_t);
int ubuf_sound_write_double(struct ubuf *, int, int, double **, uint8_t);
int ubuf_sound_resize(struct ubuf *, int, int);
struct ubuf *ubuf_sound_copy(struct ubuf_mgr *, struct ubuf *, int, int);
int ubuf_sound_interleave(struct ubuf *, uint8_t *, int, int, uint8_t, uint8_t);
int ubuf_sound_replace(struct ubuf_mgr *, struct ubuf **, int, int);
uint64_t uclock_now(struct uclock *);
time_t uclock_mktime(struct uclock *, uint64_t);
struct uclock *uclock_use(struct uclock *);
void uclock_release(struct uclock *);
typedef void (*upump_cb)(struct upump *);
struct upump *upump_alloc(struct upump_mgr *, upump_cb, void *, enum upump_type, ...);
struct upump *upump_alloc_idler(struct upump_mgr *, upump_cb, void *);
struct upump *upump_alloc_timer(struct upump_mgr *, upump_cb, void *, uint64_t, uint64_t);
struct upump *upump_alloc_fd_read(struct upump_mgr *, upump_cb, void *, int);
struct upump *upump_alloc_fd_write(struct upump_mgr *, upump_cb, void *, int);
void upump_start(struct upump *);
void upump_stop(struct upump *);
void upump_free(struct upump *);
void upump_set_cb(struct upump *, upump_cb, void *);
struct upump_mgr *upump_mgr_use(struct upump_mgr *);
void upump_mgr_release(struct upump_mgr *);
void upump_mgr_set_opaque(struct upump_mgr *, void *);
int upump_mgr_control_va(struct upump_mgr *, int, va_list);
int upump_mgr_control(struct upump_mgr *, int, ...);
int upump_mgr_vacuum(struct upump_mgr *);
struct udict *udict_alloc(struct udict_mgr *, size_t);
int udict_control_va(struct udict *, int, va_list);
int udict_control(struct udict *, int, ...);
struct udict *udict_dup(struct udict *);
int udict_iterate(struct udict *, char const **, enum udict_type *);
int udict_get(struct udict *, char const *, enum udict_type, size_t *, uint8_t const **);
struct udict_opaque {
	uint8_t const *v;
	size_t size;
};
int udict_get_opaque(struct udict *, struct udict_opaque *, enum udict_type, char const *);
int udict_get_void(struct udict *, void *, enum udict_type, char const *);
uint64_t udict_get_uint64(uint8_t const *);
int udict_set(struct udict *, char const *, enum udict_type, size_t, uint8_t **);
int udict_set_opaque(struct udict *, struct udict_opaque, enum udict_type, char const *);
int udict_set_string(struct udict *, char const *, enum udict_type, char const *);
int udict_set_void(struct udict *, void *, enum udict_type, char const *);
int udict_set_bool(struct udict *, bool, enum udict_type, char const *);
int udict_set_small_unsigned(struct udict *, uint8_t, enum udict_type, char const *);
int udict_set_small_int(struct udict *, int8_t, enum udict_type, char const *);
void udict_set_uint64(uint8_t *, uint64_t);
int udict_set_unsigned(struct udict *, uint64_t, enum udict_type, char const *);
int udict_set_int(struct udict *, uint64_t, enum udict_type, char const *);
int udict_set_float(struct udict *, double, enum udict_type, char const *);
int udict_set_rational(struct udict *, struct urational, enum udict_type, char const *);
int udict_delete(struct udict *, enum udict_type, char const *);
int udict_name(struct udict *, enum udict_type, char const **, enum udict_type *);
void udict_free(struct udict *);
int udict_import(struct udict *, struct udict *);
struct udict *udict_copy(struct udict_mgr *, struct udict *);
int udict_cmp(struct udict *, struct udict *);
struct udict_mgr *udict_mgr_use(struct udict_mgr *);
void udict_mgr_release(struct udict_mgr *);
int udict_mgr_control_va(struct udict_mgr *, int, va_list);
int udict_mgr_control(struct udict_mgr *, int, ...);
int udict_mgr_vacuum(struct udict_mgr *);
void uref_free(struct uref *);
void uref_init(struct uref *);
struct uref *uref_alloc(struct uref_mgr *);
struct uref *uref_sibling_alloc(struct uref *);
struct uref *uref_alloc_control(struct uref_mgr *);
struct uref *uref_sibling_alloc_control(struct uref *);
struct uref *uref_dup_inner(struct uref *);
struct uref *uref_dup(struct uref *);
void uref_attach_ubuf(struct uref *, struct ubuf *);
struct ubuf *uref_detach_ubuf(struct uref *);
struct uref_mgr *uref_mgr_use(struct uref_mgr *);
void uref_mgr_release(struct uref_mgr *);
int uref_mgr_control_va(struct uref_mgr *, int, va_list);
int uref_mgr_control(struct uref_mgr *, int, ...);
int uref_mgr_vacuum(struct uref_mgr *);
int uref_attr_import(struct uref *, struct uref *);
int uref_attr_get_opaque(struct uref *, struct udict_opaque *, enum udict_type, char const *);
int uref_attr_get_opaque_va(struct uref *, struct udict_opaque *, enum udict_type, char const *, ...);
int uref_attr_set_opaque(struct uref *, struct udict_opaque, enum udict_type, char const *);
int uref_attr_set_opaque_va(struct uref *, struct udict_opaque, enum udict_type, char const *, ...);
int uref_attr_get_string(struct uref *, char const **, enum udict_type, char const *);
int uref_attr_get_string_va(struct uref *, char const **, enum udict_type, char const *, ...);
int uref_attr_set_string(struct uref *, char const *, enum udict_type, char const *);
int uref_attr_set_string_va(struct uref *, char const *, enum udict_type, char const *, ...);
int uref_attr_get_void(struct uref *, void **, enum udict_type, char const *);
int uref_attr_get_void_va(struct uref *, void **, enum udict_type, char const *, ...);
int uref_attr_set_void(struct uref *, void *, enum udict_type, char const *);
int uref_attr_set_void_va(struct uref *, void *, enum udict_type, char const *, ...);
int uref_attr_get_bool(struct uref *, bool *, enum udict_type, char const *);
int uref_attr_get_bool_va(struct uref *, bool *, enum udict_type, char const *, ...);
int uref_attr_set_bool(struct uref *, bool, enum udict_type, char const *);
int uref_attr_set_bool_va(struct uref *, bool, enum udict_type, char const *, ...);
int uref_attr_get_small_unsigned(struct uref *, uint8_t *, enum udict_type, char const *);
int uref_attr_get_small_unsigned_va(struct uref *, uint8_t *, enum udict_type, char const *, ...);
int uref_attr_set_small_unsigned(struct uref *, uint8_t, enum udict_type, char const *);
int uref_attr_set_small_unsigned_va(struct uref *, uint8_t, enum udict_type, char const *, ...);
int uref_attr_get_small_int(struct uref *, int8_t *, enum udict_type, char const *);
int uref_attr_get_small_int_va(struct uref *, int8_t *, enum udict_type, char const *, ...);
int uref_attr_set_small_int(struct uref *, int8_t, enum udict_type, char const *);
int uref_attr_set_small_int_va(struct uref *, int8_t, enum udict_type, char const *, ...);
int uref_attr_get_unsigned(struct uref *, uint64_t *, enum udict_type, char const *);
int uref_attr_get_unsigned_va(struct uref *, uint64_t *, enum udict_type, char const *, ...);
int uref_attr_set_unsigned(struct uref *, uint64_t, enum udict_type, char const *);
int uref_attr_set_unsigned_va(struct uref *, uint64_t, enum udict_type, char const *, ...);
int uref_attr_get_int(struct uref *, int64_t *, enum udict_type, char const *);
int uref_attr_get_int_va(struct uref *, int64_t *, enum udict_type, char const *, ...);
int uref_attr_set_int(struct uref *, int64_t, enum udict_type, char const *);
int uref_attr_set_int_va(struct uref *, int64_t, enum udict_type, char const *, ...);
int uref_attr_get_float(struct uref *, double *, enum udict_type, char const *);
int uref_attr_get_float_va(struct uref *, double *, enum udict_type, char const *, ...);
int uref_attr_set_float(struct uref *, double, enum udict_type, char const *);
int uref_attr_set_float_va(struct uref *, double, enum udict_type, char const *, ...);
int uref_attr_get_rational(struct uref *, struct urational *, enum udict_type, char const *);
int uref_attr_get_rational_va(struct uref *, struct urational *, enum udict_type, char const *, ...);
int uref_attr_set_rational(struct uref *, struct urational, enum udict_type, char const *);
int uref_attr_set_rational_va(struct uref *, struct urational, enum udict_type, char const *, ...);
int uref_attr_delete(struct uref *, enum udict_type, char const *);
int uref_attr_delete_va(struct uref *, enum udict_type, char const *, ...);
int uref_attr_get_priv(struct uref *, uint64_t *);
void uref_attr_set_priv(struct uref *, uint64_t);
void uref_attr_delete_priv(struct uref *);
int uref_attr_match_priv(struct uref *, uint8_t, uint8_t);
int uref_attr_cmp_priv(struct uref *, struct uref *);
int uref_flow_get_end(struct uref *);
void uref_flow_set_end(struct uref *);
void uref_flow_delete_end(struct uref *);
int uref_flow_get_discontinuity(struct uref *);
void uref_flow_set_discontinuity(struct uref *);
void uref_flow_delete_discontinuity(struct uref *);
int uref_flow_get_random(struct uref *);
int uref_flow_set_random(struct uref *);
int uref_flow_delete_random(struct uref *);
int uref_flow_cmp_random(struct uref *, struct uref *);
int uref_flow_get_error(struct uref *);
int uref_flow_set_error(struct uref *);
int uref_flow_delete_error(struct uref *);
int uref_flow_cmp_error(struct uref *, struct uref *);
int uref_flow_get_def(struct uref *, char const **);
int uref_flow_set_def(struct uref *, char const *);
int uref_flow_delete_def(struct uref *);
int uref_flow_match_def(struct uref *, char const *);
int uref_flow_cmp_def(struct uref *, struct uref *);
int uref_flow_get_id(struct uref *, uint64_t *);
int uref_flow_set_id(struct uref *, uint64_t);
int uref_flow_delete_id(struct uref *);
int uref_flow_match_id(struct uref *, uint64_t, uint64_t);
int uref_flow_cmp_id(struct uref *, struct uref *);
int uref_flow_get_raw_def(struct uref *, char const **);
int uref_flow_set_raw_def(struct uref *, char const *);
int uref_flow_delete_raw_def(struct uref *);
int uref_flow_match_raw_def(struct uref *, char const *);
int uref_flow_cmp_raw_def(struct uref *, struct uref *);
int uref_flow_get_languages(struct uref *, uint8_t *);
int uref_flow_set_languages(struct uref *, uint8_t);
int uref_flow_delete_languages(struct uref *);
int uref_flow_match_languages(struct uref *, uint8_t, uint8_t);
int uref_flow_cmp_languages(struct uref *, struct uref *);
int uref_flow_get_language(struct uref *, char const **, uint8_t);
int uref_flow_set_language(struct uref *, char const *, uint8_t);
int uref_flow_delete_language(struct uref *, uint8_t);
int uref_flow_match_language(struct uref *, char const *, uint8_t);
int uref_flow_cmp_language(struct uref *, struct uref *, uint8_t);
int uref_flow_get_hearing_impaired(struct uref *, uint8_t);
int uref_flow_set_hearing_impaired(struct uref *, uint8_t);
int uref_flow_delete_hearing_impaired(struct uref *, uint8_t);
int uref_flow_cmp_hearing_impaired(struct uref *, struct uref *, uint8_t);
int uref_flow_get_visual_impaired(struct uref *, uint8_t);
int uref_flow_set_visual_impaired(struct uref *, uint8_t);
int uref_flow_delete_visual_impaired(struct uref *, uint8_t);
int uref_flow_cmp_visual_impaired(struct uref *, struct uref *, uint8_t);
int uref_flow_get_audio_clean(struct uref *, uint8_t);
int uref_flow_set_audio_clean(struct uref *, uint8_t);
int uref_flow_delete_audio_clean(struct uref *, uint8_t);
int uref_flow_cmp_audio_clean(struct uref *, struct uref *, uint8_t);
int uref_flow_get_lowdelay(struct uref *);
int uref_flow_set_lowdelay(struct uref *);
int uref_flow_delete_lowdelay(struct uref *);
int uref_flow_cmp_lowdelay(struct uref *, struct uref *);
int uref_flow_get_copyright(struct uref *);
int uref_flow_set_copyright(struct uref *);
int uref_flow_delete_copyright(struct uref *);
int uref_flow_cmp_copyright(struct uref *, struct uref *);
int uref_flow_get_original(struct uref *);
int uref_flow_set_original(struct uref *);
int uref_flow_delete_original(struct uref *);
int uref_flow_cmp_original(struct uref *, struct uref *);
int uref_flow_get_headers(struct uref *, uint8_t const **, size_t *);
int uref_flow_set_headers(struct uref *, uint8_t const *, size_t);
int uref_flow_delete_headers(struct uref *);
int uref_flow_get_name(struct uref *, char const **);
int uref_flow_set_name(struct uref *, char const *);
int uref_flow_delete_name(struct uref *);
int uref_flow_match_name(struct uref *, char const *);
int uref_flow_cmp_name(struct uref *, struct uref *);
int uref_flow_set_def_va(struct uref *, char const *, ...);
char const *uprobe_event_str(int);
struct uprobe *uprobe_use(struct uprobe *);
void uprobe_release(struct uprobe *);
bool uprobe_single(struct uprobe *);
bool uprobe_dead(struct uprobe *);
void uprobe_init(struct uprobe *, uprobe_throw_func, struct uprobe *);
void uprobe_clean(struct uprobe *);
int uprobe_throw_va(struct uprobe *, struct upipe *, int, va_list);
int uprobe_throw(struct uprobe *, struct upipe *, int, ...);
int uprobe_throw_next(struct uprobe *, struct upipe *, int, va_list);
void uprobe_log(struct uprobe *, struct upipe *, enum uprobe_log_level, char const *);
void uprobe_log_va(struct uprobe *, struct upipe *, enum uprobe_log_level, char const *, ...);
void uprobe_err_va(struct uprobe *, struct upipe *, char const *, ...);
void uprobe_warn_va(struct uprobe *, struct upipe *, char const *, ...);
void uprobe_notice_va(struct uprobe *, struct upipe *, char const *, ...);
void uprobe_dbg_va(struct uprobe *, struct upipe *, char const *, ...);
void uprobe_verbose_va(struct uprobe *, struct upipe *, char const *, ...);
bool uprobe_plumber(int, va_list, struct uref **, char const **);
void udict_dump(struct udict *, struct uprobe *);
void urequest_init_uref_mgr(struct urequest *, urequest_func, urequest_free_func);
void urequest_init_flow_format(struct urequest *, struct uref *, urequest_func, urequest_free_func);
void urequest_init_ubuf_mgr(struct urequest *, struct uref *, urequest_func, urequest_free_func);
void urequest_init_uclock(struct urequest *, urequest_func, urequest_free_func);
void urequest_init_sink_latency(struct urequest *, urequest_func, urequest_free_func);
void urequest_clean(struct urequest *);
void urequest_free(struct urequest *);
void urequest_set_opaque(struct urequest *, void *);
int urequest_provide_va(struct urequest *, va_list);
int urequest_provide(struct urequest *, ...);
int urequest_provide_uref_mgr(struct urequest *, struct uref_mgr *);
int urequest_provide_flow_format(struct urequest *, struct uref *);
int urequest_provide_ubuf_mgr(struct urequest *, struct ubuf_mgr *, struct uref *);
int urequest_provide_uclock(struct urequest *, struct uclock *);
int urequest_provide_sink_latency(struct urequest *, uint64_t);
struct upipe_mgr *upipe_mgr_use(struct upipe_mgr *);
void upipe_mgr_release(struct upipe_mgr *);
int upipe_mgr_control_va(struct upipe_mgr *, int, va_list);
int upipe_mgr_control(struct upipe_mgr *, int, ...);
int upipe_mgr_vacuum(struct upipe_mgr *);
char const *upipe_err_str(struct upipe *, int);
char const *upipe_command_str(struct upipe *, int);
char const *upipe_event_str(struct upipe *, int);
struct upipe *upipe_alloc_va(struct upipe_mgr *, struct uprobe *, uint32_t, va_list);
struct upipe *upipe_alloc(struct upipe_mgr *, struct uprobe *, uint32_t, ...);
void upipe_init(struct upipe *, struct upipe_mgr *, struct uprobe *);
struct upipe *upipe_use(struct upipe *);
void upipe_release(struct upipe *);
bool upipe_single(struct upipe *);
bool upipe_dead(struct upipe *);
void upipe_set_opaque(struct upipe *, void *);
void upipe_push_probe(struct upipe *, struct uprobe *);
struct uprobe *upipe_pop_probe(struct upipe *);
void upipe_clean(struct upipe *);
int upipe_throw_va(struct upipe *, int, va_list);
int upipe_throw(struct upipe *, int, ...);
void upipe_log_va(struct upipe *, enum uprobe_log_level, char const *, ...);
void upipe_err_va(struct upipe *, char const *, ...);
void upipe_warn_va(struct upipe *, char const *, ...);
void upipe_notice_va(struct upipe *, char const *, ...);
void upipe_dbg_va(struct upipe *, char const *, ...);
void upipe_verbose_va(struct upipe *, char const *, ...);
int upipe_throw_ready(struct upipe *);
int upipe_throw_dead(struct upipe *);
int upipe_throw_source_end(struct upipe *);
int upipe_throw_sink_end(struct upipe *);
int upipe_throw_need_output(struct upipe *, struct uref *);
int upipe_throw_provide_request(struct upipe *, struct urequest *);
int upipe_throw_need_upump_mgr(struct upipe *, struct upump_mgr **);
int upipe_throw_freeze_upump_mgr(struct upipe *);
int upipe_throw_thaw_upump_mgr(struct upipe *);
int upipe_throw_new_flow_def(struct upipe *, struct uref *);
int upipe_throw_new_rap(struct upipe *, struct uref *);
int upipe_split_throw_update(struct upipe *);
int upipe_throw_sync_acquired(struct upipe *);
int upipe_throw_sync_lost(struct upipe *);
int upipe_throw_clock_ref(struct upipe *, struct uref *, uint64_t, int);
int upipe_throw_clock_ts(struct upipe *, struct uref *);
int upipe_throw_clock_utc(struct upipe *, struct uref *, uint64_t);
int upipe_throw_proxy(struct upipe *, struct upipe *, int, va_list);
void upipe_input(struct upipe *, struct uref *, struct upump **);
int upipe_control_va(struct upipe *, int, va_list);
int upipe_control_nodbg(struct upipe *, int, ...);
int upipe_control(struct upipe *, int, ...);
int upipe_get_uri(struct upipe *, char const **);
int upipe_set_uri(struct upipe *, char const *);
int upipe_get_flow_def(struct upipe *, struct uref **);
int upipe_set_flow_def(struct upipe *, struct uref *);
int upipe_get_output(struct upipe *, struct upipe **);
int upipe_set_output(struct upipe *, struct upipe *);
int upipe_get_max_length(struct upipe *, unsigned int *);
int upipe_set_max_length(struct upipe *, unsigned int);
int upipe_get_output_size(struct upipe *, unsigned int *);
int upipe_set_output_size(struct upipe *, unsigned int);
int upipe_get_option(struct upipe *, char const *, char const **);
int upipe_set_option(struct upipe *, char const *, char const *);
int upipe_attach_uref_mgr(struct upipe *);
int upipe_attach_upump_mgr(struct upipe *);
int upipe_attach_uclock(struct upipe *);
int upipe_attach_ubuf_mgr(struct upipe *);
int upipe_register_request(struct upipe *, struct urequest *);
int upipe_unregister_request(struct upipe *, struct urequest *);
int upipe_flush(struct upipe *);
int upipe_sink_flush(struct upipe *);
int upipe_split_iterate(struct upipe *, struct uref **);
int upipe_get_sub_mgr(struct upipe *, struct upipe_mgr **);
int upipe_iterate_sub(struct upipe *, struct upipe **);
int upipe_sub_get_super(struct upipe *, struct upipe **);
struct upipe *upipe_void_alloc(struct upipe_mgr *, struct uprobe *);
struct upipe *upipe_void_alloc_output(struct upipe *, struct upipe_mgr *, struct uprobe *);
struct upipe *upipe_void_chain_output(struct upipe *, struct upipe_mgr *, struct uprobe *);
int upipe_void_spawn_output(struct upipe *, struct upipe_mgr *, struct uprobe *);
struct upipe *upipe_void_alloc_input(struct upipe *, struct upipe_mgr *, struct uprobe *);
struct upipe *upipe_void_chain_input(struct upipe *, struct upipe_mgr *, struct uprobe *);
struct upipe *upipe_void_alloc_sub(struct upipe *, struct uprobe *);
struct upipe *upipe_void_alloc_output_sub(struct upipe *, struct upipe *, struct uprobe *);
struct upipe *upipe_void_chain_output_sub(struct upipe *, struct upipe *, struct uprobe *);
int upipe_void_spawn_output_sub(struct upipe *, struct upipe *, struct uprobe *);
struct upipe *upipe_void_alloc_input_sub(struct upipe *, struct upipe *, struct uprobe *);
struct upipe *upipe_void_chain_input_sub(struct upipe *, struct upipe *, struct uprobe *);
struct upipe *upipe_flow_alloc(struct upipe_mgr *, struct uprobe *, struct uref *);
struct upipe *upipe_flow_alloc_output(struct upipe *, struct upipe_mgr *, struct uprobe *, struct uref *);
struct upipe *upipe_flow_chain_output(struct upipe *, struct upipe_mgr *, struct uprobe *, struct uref *);
int upipe_flow_spawn_output(struct upipe *, struct upipe_mgr *, struct uprobe *, struct uref *);
struct upipe *upipe_flow_alloc_input(struct upipe *, struct upipe_mgr *, struct uprobe *, struct uref *);
struct upipe *upipe_flow_chain_input(struct upipe *, struct upipe_mgr *, struct uprobe *, struct uref *);
struct upipe *upipe_flow_alloc_sub(struct upipe *, struct uprobe *, struct uref *);
struct upipe *upipe_flow_alloc_output_sub(struct upipe *, struct upipe *, struct uprobe *, struct uref *);
struct upipe *upipe_flow_chain_output_sub(struct upipe *, struct upipe *, struct uprobe *, struct uref *);
int upipe_flow_spawn_output_sub(struct upipe *, struct upipe *, struct uprobe *, struct uref *);
struct upipe *upipe_flow_alloc_input_sub(struct upipe *, struct upipe *, struct uprobe *, struct uref *);
struct upipe *upipe_flow_chain_input_sub(struct upipe *, struct upipe *, struct uprobe *, struct uref *);
struct upump_blocker *upump_blocker_from_uchain(struct uchain *);
struct uchain *upump_blocker_to_uchain(struct upump_blocker *);
typedef void (*upump_blocker_cb)(struct upump_blocker *);
struct upump_blocker *upump_blocker_alloc(struct upump *, upump_blocker_cb, void *);
void upump_blocker_free(struct upump_blocker *);
void upump_blocker_set_cb(struct upump_blocker *, upump_blocker_cb, void *);
struct upump_blocker *upump_blocker_find(struct uchain *, struct upump *);
int uref_block_flow_get_octetrate(struct uref *, uint64_t *);
int uref_block_flow_set_octetrate(struct uref *, uint64_t);
int uref_block_flow_delete_octetrate(struct uref *);
int uref_block_flow_match_octetrate(struct uref *, uint64_t, uint64_t);
int uref_block_flow_cmp_octetrate(struct uref *, struct uref *);
int uref_block_flow_get_max_octetrate(struct uref *, uint64_t *);
int uref_block_flow_set_max_octetrate(struct uref *, uint64_t);
int uref_block_flow_delete_max_octetrate(struct uref *);
int uref_block_flow_match_max_octetrate(struct uref *, uint64_t, uint64_t);
int uref_block_flow_cmp_max_octetrate(struct uref *, struct uref *);
int uref_block_flow_get_buffer_size(struct uref *, uint64_t *);
int uref_block_flow_set_buffer_size(struct uref *, uint64_t);
int uref_block_flow_delete_buffer_size(struct uref *);
int uref_block_flow_match_buffer_size(struct uref *, uint64_t, uint64_t);
int uref_block_flow_cmp_buffer_size(struct uref *, struct uref *);
int uref_block_flow_get_max_buffer_size(struct uref *, uint64_t *);
int uref_block_flow_set_max_buffer_size(struct uref *, uint64_t);
int uref_block_flow_delete_max_buffer_size(struct uref *);
int uref_block_flow_match_max_buffer_size(struct uref *, uint64_t, uint64_t);
int uref_block_flow_cmp_max_buffer_size(struct uref *, struct uref *);
int uref_block_flow_get_align(struct uref *, uint64_t *);
int uref_block_flow_set_align(struct uref *, uint64_t);
int uref_block_flow_delete_align(struct uref *);
int uref_block_flow_match_align(struct uref *, uint64_t, uint64_t);
int uref_block_flow_cmp_align(struct uref *, struct uref *);
int uref_block_flow_get_align_offset(struct uref *, int64_t *);
int uref_block_flow_set_align_offset(struct uref *, int64_t);
int uref_block_flow_delete_align_offset(struct uref *);
int uref_block_flow_cmp_align_offset(struct uref *, struct uref *);
int uref_block_flow_get_size(struct uref *, uint64_t *);
int uref_block_flow_set_size(struct uref *, uint64_t);
int uref_block_flow_delete_size(struct uref *);
int uref_block_flow_match_size(struct uref *, uint64_t, uint64_t);
int uref_block_flow_cmp_size(struct uref *, struct uref *);
struct uref *uref_block_flow_alloc_def(struct uref_mgr *, char const *);
struct uref *uref_block_flow_alloc_def_va(struct uref_mgr *, char const *, ...);
void uref_block_flow_clear_format(struct uref *);
int uref_block_get_start(struct uref *);
void uref_block_set_start(struct uref *);
void uref_block_delete_start(struct uref *);
int uref_block_get_end(struct uref *);
void uref_block_set_end(struct uref *);
void uref_block_delete_end(struct uref *);
int uref_block_get_header_size(struct uref *, uint64_t *);
int uref_block_set_header_size(struct uref *, uint64_t);
int uref_block_delete_header_size(struct uref *);
int uref_block_match_header_size(struct uref *, uint64_t, uint64_t);
int uref_block_cmp_header_size(struct uref *, struct uref *);
struct uref *uref_block_alloc(struct uref_mgr *, struct ubuf_mgr *, int);
int uref_block_size(struct uref *, size_t *);
int uref_block_size_linear(struct uref *, int, size_t *);
int uref_block_read(struct uref *, int, int *, uint8_t const **);
int uref_block_write(struct uref *, int, int *, uint8_t **);
int uref_block_unmap(struct uref *, int);
int uref_block_insert(struct uref *, int, struct ubuf *);
int uref_block_append(struct uref *, struct ubuf *);
int uref_block_delete(struct uref *, int, int);
int uref_block_truncate(struct uref *, int);
int uref_block_resize(struct uref *, int, int);
struct uref *uref_block_splice(struct uref *, int, int);
uint8_t const *uref_block_peek(struct uref *, int, int, uint8_t *);
int uref_block_peek_unmap(struct uref *, int, uint8_t *, uint8_t const *);
int uref_block_extract(struct uref *, int, int, uint8_t *);
int uref_block_iovec_count(struct uref *, int, int);
int uref_block_iovec_read(struct uref *, int, int, struct iovec *);
int uref_block_iovec_unmap(struct uref *, int, int, struct iovec *);
int uref_block_merge(struct uref *, struct ubuf_mgr *, int, int);
int uref_block_compare(struct uref *, int, struct uref *);
int uref_block_equal(struct uref *, struct uref *);
int uref_block_match(struct uref *, uint8_t const *, uint8_t const *, size_t);
int uref_block_scan(struct uref *, size_t *, uint8_t);
int uref_block_find_va(struct uref *, size_t *, unsigned int, va_list);
int uref_block_find(struct uref *, size_t *, unsigned int, ...);
int uref_clock_get_ref(struct uref *);
void uref_clock_set_ref(struct uref *);
void uref_clock_delete_ref(struct uref *);
int uref_clock_get_dts_pts_delay(struct uref *, uint64_t *);
void uref_clock_set_dts_pts_delay(struct uref *, uint64_t);
void uref_clock_delete_dts_pts_delay(struct uref *);
int uref_clock_match_dts_pts_delay(struct uref *, uint8_t, uint8_t);
int uref_clock_cmp_dts_pts_delay(struct uref *, struct uref *);
int uref_clock_get_cr_dts_delay(struct uref *, uint64_t *);
void uref_clock_set_cr_dts_delay(struct uref *, uint64_t);
void uref_clock_delete_cr_dts_delay(struct uref *);
int uref_clock_match_cr_dts_delay(struct uref *, uint8_t, uint8_t);
int uref_clock_cmp_cr_dts_delay(struct uref *, struct uref *);
int uref_clock_get_rap_cr_delay(struct uref *, uint64_t *);
void uref_clock_set_rap_cr_delay(struct uref *, uint64_t);
void uref_clock_delete_rap_cr_delay(struct uref *);
int uref_clock_match_rap_cr_delay(struct uref *, uint8_t, uint8_t);
int uref_clock_cmp_rap_cr_delay(struct uref *, struct uref *);
int uref_clock_get_duration(struct uref *, uint64_t *);
int uref_clock_set_duration(struct uref *, uint64_t);
int uref_clock_delete_duration(struct uref *);
int uref_clock_match_duration(struct uref *, uint64_t, uint64_t);
int uref_clock_cmp_duration(struct uref *, struct uref *);
int uref_clock_get_index_rap(struct uref *, uint8_t *);
int uref_clock_set_index_rap(struct uref *, uint8_t);
int uref_clock_delete_index_rap(struct uref *);
int uref_clock_match_index_rap(struct uref *, uint8_t, uint8_t);
int uref_clock_cmp_index_rap(struct uref *, struct uref *);
int uref_clock_get_rate(struct uref *, struct urational *);
int uref_clock_set_rate(struct uref *, struct urational);
int uref_clock_delete_rate(struct uref *);
int uref_clock_get_latency(struct uref *, uint64_t *);
int uref_clock_set_latency(struct uref *, uint64_t);
int uref_clock_delete_latency(struct uref *);
int uref_clock_match_latency(struct uref *, uint64_t, uint64_t);
int uref_clock_cmp_latency(struct uref *, struct uref *);
void uref_clock_get_date_sys(struct uref const *, uint64_t *, int *);
void uref_clock_set_date_sys(struct uref *, uint64_t, int);
void uref_clock_delete_date_sys(struct uref *);
void uref_clock_get_date_prog(struct uref const *, uint64_t *, int *);
void uref_clock_set_date_prog(struct uref *, uint64_t, int);
void uref_clock_delete_date_prog(struct uref *);
void uref_clock_get_date_orig(struct uref const *, uint64_t *, int *);
void uref_clock_set_date_orig(struct uref *, uint64_t, int);
void uref_clock_delete_date_orig(struct uref *);
void uref_clock_set_cr_sys(struct uref *, uint64_t);
void uref_clock_set_cr_prog(struct uref *, uint64_t);
void uref_clock_set_cr_orig(struct uref *, uint64_t);
void uref_clock_set_dts_sys(struct uref *, uint64_t);
void uref_clock_set_dts_prog(struct uref *, uint64_t);
void uref_clock_set_dts_orig(struct uref *, uint64_t);
void uref_clock_set_pts_sys(struct uref *, uint64_t);
void uref_clock_set_pts_prog(struct uref *, uint64_t);
void uref_clock_set_pts_orig(struct uref *, uint64_t);
int uref_clock_get_pts_sys(struct uref *, uint64_t *);
int uref_clock_get_pts_prog(struct uref *, uint64_t *);
int uref_clock_get_pts_orig(struct uref *, uint64_t *);
int uref_clock_get_dts_sys(struct uref *, uint64_t *);
int uref_clock_get_dts_prog(struct uref *, uint64_t *);
int uref_clock_get_dts_orig(struct uref *, uint64_t *);
int uref_clock_get_cr_sys(struct uref *, uint64_t *);
int uref_clock_get_cr_prog(struct uref *, uint64_t *);
int uref_clock_get_cr_orig(struct uref *, uint64_t *);
int uref_clock_get_rap_sys(struct uref *, uint64_t *);
int uref_clock_get_rap_prog(struct uref *, uint64_t *);
int uref_clock_get_rap_orig(struct uref *, uint64_t *);
int uref_clock_set_rap_sys(struct uref *, uint64_t);
int uref_clock_set_rap_prog(struct uref *, uint64_t);
int uref_clock_set_rap_orig(struct uref *, uint64_t);
int uref_clock_rebase_cr_sys(struct uref *);
int uref_clock_rebase_cr_prog(struct uref *);
int uref_clock_rebase_cr_orig(struct uref *);
int uref_clock_rebase_dts_sys(struct uref *);
int uref_clock_rebase_dts_prog(struct uref *);
int uref_clock_rebase_dts_orig(struct uref *);
int uref_clock_rebase_pts_sys(struct uref *);
int uref_clock_rebase_pts_prog(struct uref *);
int uref_clock_rebase_pts_orig(struct uref *);
void uref_dump(struct uref *, struct uprobe *);
int uref_event_get_events(struct uref *, uint64_t *);
int uref_event_set_events(struct uref *, uint64_t);
int uref_event_delete_events(struct uref *);
int uref_event_match_events(struct uref *, uint64_t, uint64_t);
int uref_event_cmp_events(struct uref *, struct uref *);
int uref_event_get_id(struct uref *, uint64_t *, uint64_t);
int uref_event_set_id(struct uref *, uint64_t, uint64_t);
int uref_event_delete_id(struct uref *, uint64_t);
int uref_event_match_id(struct uref *, uint8_t, uint8_t, uint64_t);
int uref_event_cmp_id(struct uref *, struct uref *, uint64_t);
int uref_event_get_start(struct uref *, uint64_t *, uint64_t);
int uref_event_set_start(struct uref *, uint64_t, uint64_t);
int uref_event_delete_start(struct uref *, uint64_t);
int uref_event_match_start(struct uref *, uint8_t, uint8_t, uint64_t);
int uref_event_cmp_start(struct uref *, struct uref *, uint64_t);
int uref_event_get_duration(struct uref *, uint64_t *, uint64_t);
int uref_event_set_duration(struct uref *, uint64_t, uint64_t);
int uref_event_delete_duration(struct uref *, uint64_t);
int uref_event_match_duration(struct uref *, uint8_t, uint8_t, uint64_t);
int uref_event_cmp_duration(struct uref *, struct uref *, uint64_t);
int uref_event_get_language(struct uref *, char const **, uint64_t);
int uref_event_set_language(struct uref *, char const *, uint64_t);
int uref_event_delete_language(struct uref *, uint64_t);
int uref_event_match_language(struct uref *, char const *, uint64_t);
int uref_event_cmp_language(struct uref *, struct uref *, uint64_t);
int uref_event_get_name(struct uref *, char const **, uint64_t);
int uref_event_set_name(struct uref *, char const *, uint64_t);
int uref_event_delete_name(struct uref *, uint64_t);
int uref_event_match_name(struct uref *, char const *, uint64_t);
int uref_event_cmp_name(struct uref *, struct uref *, uint64_t);
int uref_event_get_description(struct uref *, char const **, uint64_t);
int uref_event_set_description(struct uref *, char const *, uint64_t);
int uref_event_delete_description(struct uref *, uint64_t);
int uref_event_match_description(struct uref *, char const *, uint64_t);
int uref_event_cmp_description(struct uref *, struct uref *, uint64_t);
int uref_pic_flow_get_macropixel(struct uref *, uint8_t *);
int uref_pic_flow_set_macropixel(struct uref *, uint8_t);
int uref_pic_flow_delete_macropixel(struct uref *);
int uref_pic_flow_match_macropixel(struct uref *, uint8_t, uint8_t);
int uref_pic_flow_cmp_macropixel(struct uref *, struct uref *);
int uref_pic_flow_get_planes(struct uref *, uint8_t *);
int uref_pic_flow_set_planes(struct uref *, uint8_t);
int uref_pic_flow_delete_planes(struct uref *);
int uref_pic_flow_match_planes(struct uref *, uint8_t, uint8_t);
int uref_pic_flow_cmp_planes(struct uref *, struct uref *);
int uref_pic_flow_get_hsubsampling(struct uref *, uint8_t *, uint8_t);
int uref_pic_flow_set_hsubsampling(struct uref *, uint8_t, uint8_t);
int uref_pic_flow_delete_hsubsampling(struct uref *, uint8_t);
int uref_pic_flow_match_hsubsampling(struct uref *, uint8_t, uint8_t, uint8_t);
int uref_pic_flow_cmp_hsubsampling(struct uref *, struct uref *, uint8_t);
int uref_pic_flow_get_vsubsampling(struct uref *, uint8_t *, uint8_t);
int uref_pic_flow_set_vsubsampling(struct uref *, uint8_t, uint8_t);
int uref_pic_flow_delete_vsubsampling(struct uref *, uint8_t);
int uref_pic_flow_match_vsubsampling(struct uref *, uint8_t, uint8_t, uint8_t);
int uref_pic_flow_cmp_vsubsampling(struct uref *, struct uref *, uint8_t);
int uref_pic_flow_get_macropixel_size(struct uref *, uint8_t *, uint8_t);
int uref_pic_flow_set_macropixel_size(struct uref *, uint8_t, uint8_t);
int uref_pic_flow_delete_macropixel_size(struct uref *, uint8_t);
int uref_pic_flow_match_macropixel_size(struct uref *, uint8_t, uint8_t, uint8_t);
int uref_pic_flow_cmp_macropixel_size(struct uref *, struct uref *, uint8_t);
int uref_pic_flow_get_chroma(struct uref *, char const **, uint8_t);
int uref_pic_flow_set_chroma(struct uref *, char const *, uint8_t);
int uref_pic_flow_delete_chroma(struct uref *, uint8_t);
int uref_pic_flow_match_chroma(struct uref *, char const *, uint8_t);
int uref_pic_flow_cmp_chroma(struct uref *, struct uref *, uint8_t);
int uref_pic_flow_get_fps(struct uref *, struct urational *);
int uref_pic_flow_set_fps(struct uref *, struct urational);
int uref_pic_flow_delete_fps(struct uref *);
int uref_pic_flow_get_hmprepend(struct uref *, uint8_t *);
int uref_pic_flow_set_hmprepend(struct uref *, uint8_t);
int uref_pic_flow_delete_hmprepend(struct uref *);
int uref_pic_flow_match_hmprepend(struct uref *, uint8_t, uint8_t);
int uref_pic_flow_cmp_hmprepend(struct uref *, struct uref *);
int uref_pic_flow_get_hmappend(struct uref *, uint8_t *);
int uref_pic_flow_set_hmappend(struct uref *, uint8_t);
int uref_pic_flow_delete_hmappend(struct uref *);
int uref_pic_flow_match_hmappend(struct uref *, uint8_t, uint8_t);
int uref_pic_flow_cmp_hmappend(struct uref *, struct uref *);
int uref_pic_flow_get_vprepend(struct uref *, uint8_t *);
int uref_pic_flow_set_vprepend(struct uref *, uint8_t);
int uref_pic_flow_delete_vprepend(struct uref *);
int uref_pic_flow_match_vprepend(struct uref *, uint8_t, uint8_t);
int uref_pic_flow_cmp_vprepend(struct uref *, struct uref *);
int uref_pic_flow_get_vappend(struct uref *, uint8_t *);
int uref_pic_flow_set_vappend(struct uref *, uint8_t);
int uref_pic_flow_delete_vappend(struct uref *);
int uref_pic_flow_match_vappend(struct uref *, uint8_t, uint8_t);
int uref_pic_flow_cmp_vappend(struct uref *, struct uref *);
int uref_pic_flow_get_align(struct uref *, uint64_t *);
int uref_pic_flow_set_align(struct uref *, uint64_t);
int uref_pic_flow_delete_align(struct uref *);
int uref_pic_flow_match_align(struct uref *, uint64_t, uint64_t);
int uref_pic_flow_cmp_align(struct uref *, struct uref *);
int uref_pic_flow_get_align_hmoffset(struct uref *, int64_t *);
int uref_pic_flow_set_align_hmoffset(struct uref *, int64_t);
int uref_pic_flow_delete_align_hmoffset(struct uref *);
int uref_pic_flow_cmp_align_hmoffset(struct uref *, struct uref *);
int uref_pic_flow_get_sar(struct uref *, struct urational *);
int uref_pic_flow_set_sar(struct uref *, struct urational);
int uref_pic_flow_delete_sar(struct uref *);
int uref_pic_flow_get_overscan(struct uref *);
int uref_pic_flow_set_overscan(struct uref *);
int uref_pic_flow_delete_overscan(struct uref *);
int uref_pic_flow_cmp_overscan(struct uref *, struct uref *);
int uref_pic_flow_get_hsize(struct uref *, uint64_t *);
int uref_pic_flow_set_hsize(struct uref *, uint64_t);
int uref_pic_flow_delete_hsize(struct uref *);
int uref_pic_flow_match_hsize(struct uref *, uint64_t, uint64_t);
int uref_pic_flow_cmp_hsize(struct uref *, struct uref *);
int uref_pic_flow_get_vsize(struct uref *, uint64_t *);
int uref_pic_flow_set_vsize(struct uref *, uint64_t);
int uref_pic_flow_delete_vsize(struct uref *);
int uref_pic_flow_match_vsize(struct uref *, uint64_t, uint64_t);
int uref_pic_flow_cmp_vsize(struct uref *, struct uref *);
int uref_pic_flow_get_hsize_visible(struct uref *, uint64_t *);
int uref_pic_flow_set_hsize_visible(struct uref *, uint64_t);
int uref_pic_flow_delete_hsize_visible(struct uref *);
int uref_pic_flow_match_hsize_visible(struct uref *, uint64_t, uint64_t);
int uref_pic_flow_cmp_hsize_visible(struct uref *, struct uref *);
int uref_pic_flow_get_vsize_visible(struct uref *, uint64_t *);
int uref_pic_flow_set_vsize_visible(struct uref *, uint64_t);
int uref_pic_flow_delete_vsize_visible(struct uref *);
int uref_pic_flow_match_vsize_visible(struct uref *, uint64_t, uint64_t);
int uref_pic_flow_cmp_vsize_visible(struct uref *, struct uref *);
int uref_pic_flow_get_video_format(struct uref *, char const **);
int uref_pic_flow_set_video_format(struct uref *, char const *);
int uref_pic_flow_delete_video_format(struct uref *);
int uref_pic_flow_match_video_format(struct uref *, char const *);
int uref_pic_flow_cmp_video_format(struct uref *, struct uref *);
int uref_pic_flow_get_full_range(struct uref *);
int uref_pic_flow_set_full_range(struct uref *);
int uref_pic_flow_delete_full_range(struct uref *);
int uref_pic_flow_cmp_full_range(struct uref *, struct uref *);
int uref_pic_flow_get_colour_primaries(struct uref *, char const **);
int uref_pic_flow_set_colour_primaries(struct uref *, char const *);
int uref_pic_flow_delete_colour_primaries(struct uref *);
int uref_pic_flow_match_colour_primaries(struct uref *, char const *);
int uref_pic_flow_cmp_colour_primaries(struct uref *, struct uref *);
int uref_pic_flow_get_transfer_characteristics(struct uref *, char const **);
int uref_pic_flow_set_transfer_characteristics(struct uref *, char const *);
int uref_pic_flow_delete_transfer_characteristics(struct uref *);
int uref_pic_flow_match_transfer_characteristics(struct uref *, char const *);
int uref_pic_flow_cmp_transfer_characteristics(struct uref *, struct uref *);
int uref_pic_flow_get_matrix_coefficients(struct uref *, char const **);
int uref_pic_flow_set_matrix_coefficients(struct uref *, char const *);
int uref_pic_flow_delete_matrix_coefficients(struct uref *);
int uref_pic_flow_match_matrix_coefficients(struct uref *, char const *);
int uref_pic_flow_cmp_matrix_coefficients(struct uref *, struct uref *);
struct uref *uref_pic_flow_alloc_def(struct uref_mgr *, uint8_t);
int uref_pic_flow_add_plane(struct uref *, uint8_t, uint8_t, uint8_t, char const *);
int uref_pic_flow_find_chroma(struct uref *, char const *, uint8_t *);
int uref_pic_flow_check_chroma(struct uref *, uint8_t, uint8_t, uint8_t, char const *);
int uref_pic_flow_copy_format(struct uref *, struct uref *);
void uref_pic_flow_clear_format(struct uref *);
bool uref_pic_flow_compare_format(struct uref *, struct uref *);
int uref_pic_flow_infer_sar(struct uref *, struct urational);
int uref_pic_get_number(struct uref *, uint64_t *);
int uref_pic_set_number(struct uref *, uint64_t);
int uref_pic_delete_number(struct uref *);
int uref_pic_match_number(struct uref *, uint64_t, uint64_t);
int uref_pic_cmp_number(struct uref *, struct uref *);
int uref_pic_get_key(struct uref *);
int uref_pic_set_key(struct uref *);
int uref_pic_delete_key(struct uref *);
int uref_pic_cmp_key(struct uref *, struct uref *);
int uref_pic_get_hposition(struct uref *, uint64_t *);
int uref_pic_set_hposition(struct uref *, uint64_t);
int uref_pic_delete_hposition(struct uref *);
int uref_pic_match_hposition(struct uref *, uint64_t, uint64_t);
int uref_pic_cmp_hposition(struct uref *, struct uref *);
int uref_pic_get_vposition(struct uref *, uint64_t *);
int uref_pic_set_vposition(struct uref *, uint64_t);
int uref_pic_delete_vposition(struct uref *);
int uref_pic_match_vposition(struct uref *, uint64_t, uint64_t);
int uref_pic_cmp_vposition(struct uref *, struct uref *);
int uref_pic_get_progressive(struct uref *);
int uref_pic_set_progressive(struct uref *);
int uref_pic_delete_progressive(struct uref *);
int uref_pic_cmp_progressive(struct uref *, struct uref *);
int uref_pic_get_tf(struct uref *);
int uref_pic_set_tf(struct uref *);
int uref_pic_delete_tf(struct uref *);
int uref_pic_cmp_tf(struct uref *, struct uref *);
int uref_pic_get_bf(struct uref *);
int uref_pic_set_bf(struct uref *);
int uref_pic_delete_bf(struct uref *);
int uref_pic_cmp_bf(struct uref *, struct uref *);
int uref_pic_get_tff(struct uref *);
int uref_pic_set_tff(struct uref *);
int uref_pic_delete_tff(struct uref *);
int uref_pic_cmp_tff(struct uref *, struct uref *);
struct uref *uref_pic_alloc(struct uref_mgr *, struct ubuf_mgr *, int, int);
int uref_pic_size(struct uref *, size_t *, size_t *, uint8_t *);
int uref_pic_plane_iterate(struct uref *, char const **);
int uref_pic_plane_size(struct uref *, char const *, size_t *, uint8_t *, uint8_t *, uint8_t *);
int uref_pic_plane_read(struct uref *, char const *, int, int, int, int, uint8_t const **);
int uref_pic_plane_write(struct uref *, char const *, int, int, int, int, uint8_t **);
int uref_pic_plane_unmap(struct uref *, char const *, int, int, int, int);
int uref_pic_plane_clear(struct uref *, char const *, int, int, int, int);
int uref_pic_resize(struct uref *, int, int, int, int);
int uref_pic_clear(struct uref *, int, int, int, int);
int uref_pic_replace(struct uref *, struct ubuf_mgr *, int, int, int, int);
int uref_program_flow_get_name(struct uref *, char const **);
int uref_program_flow_set_name(struct uref *, char const *);
int uref_program_flow_delete_name(struct uref *);
int uref_program_flow_match_name(struct uref *, char const *);
int uref_program_flow_cmp_name(struct uref *, struct uref *);
struct uref *uref_program_flow_alloc_def(struct uref_mgr *);
int uref_sound_flow_get_planes(struct uref *, uint8_t *);
int uref_sound_flow_set_planes(struct uref *, uint8_t);
int uref_sound_flow_delete_planes(struct uref *);
int uref_sound_flow_match_planes(struct uref *, uint8_t, uint8_t);
int uref_sound_flow_cmp_planes(struct uref *, struct uref *);
int uref_sound_flow_get_channel(struct uref *, char const **, uint8_t);
int uref_sound_flow_set_channel(struct uref *, char const *, uint8_t);
int uref_sound_flow_delete_channel(struct uref *, uint8_t);
int uref_sound_flow_match_channel(struct uref *, char const *, uint8_t);
int uref_sound_flow_cmp_channel(struct uref *, struct uref *, uint8_t);
int uref_sound_flow_get_channels(struct uref *, uint8_t *);
int uref_sound_flow_set_channels(struct uref *, uint8_t);
int uref_sound_flow_delete_channels(struct uref *);
int uref_sound_flow_match_channels(struct uref *, uint8_t, uint8_t);
int uref_sound_flow_cmp_channels(struct uref *, struct uref *);
int uref_sound_flow_get_sample_size(struct uref *, uint8_t *);
int uref_sound_flow_set_sample_size(struct uref *, uint8_t);
int uref_sound_flow_delete_sample_size(struct uref *);
int uref_sound_flow_match_sample_size(struct uref *, uint8_t, uint8_t);
int uref_sound_flow_cmp_sample_size(struct uref *, struct uref *);
int uref_sound_flow_get_rate(struct uref *, uint64_t *);
int uref_sound_flow_set_rate(struct uref *, uint64_t);
int uref_sound_flow_delete_rate(struct uref *);
int uref_sound_flow_match_rate(struct uref *, uint64_t, uint64_t);
int uref_sound_flow_cmp_rate(struct uref *, struct uref *);
int uref_sound_flow_get_samples(struct uref *, uint64_t *);
int uref_sound_flow_set_samples(struct uref *, uint64_t);
int uref_sound_flow_delete_samples(struct uref *);
int uref_sound_flow_match_samples(struct uref *, uint64_t, uint64_t);
int uref_sound_flow_cmp_samples(struct uref *, struct uref *);
int uref_sound_flow_get_align(struct uref *, uint64_t *);
int uref_sound_flow_set_align(struct uref *, uint64_t);
int uref_sound_flow_delete_align(struct uref *);
int uref_sound_flow_match_align(struct uref *, uint64_t, uint64_t);
int uref_sound_flow_cmp_align(struct uref *, struct uref *);
struct uref *uref_sound_flow_alloc_def(struct uref_mgr *, char const *, uint8_t, uint8_t);
int uref_sound_flow_add_plane(struct uref *, char const *);
int uref_sound_flow_find_channel(struct uref *, char const *, uint8_t *);
int uref_sound_flow_check_channel(struct uref *, char const *);
int uref_sound_flow_copy_format(struct uref *, struct uref *);
void uref_sound_flow_clear_format(struct uref *);
bool uref_sound_flow_compare_format(struct uref *, struct uref *);
struct uref *uref_sound_alloc(struct uref_mgr *, struct ubuf_mgr *, int);
int uref_sound_size(struct uref *, size_t *, uint8_t *);
int uref_sound_plane_iterate(struct uref *, char const **);
int uref_sound_plane_unmap(struct uref *, char const *, int, int);
int uref_sound_unmap(struct uref *, int, int, uint8_t);
int uref_sound_plane_read_void(struct uref *, char const *, int, int, void const **);
int uref_sound_plane_write_void(struct uref *, char const *, int, int, void **);
int uref_sound_read_void(struct uref *, int, int, void const **, uint8_t);
int uref_sound_write_void(struct uref *, int, int, void **, uint8_t);
int uref_sound_plane_read_uint8_t(struct uref *, char const *, int, int, uint8_t const **);
int uref_sound_plane_write_uint8_t(struct uref *, char const *, int, int, uint8_t **);
int uref_sound_read_uint8_t(struct uref *, int, int, uint8_t const **, uint8_t);
int uref_sound_write_uint8_t(struct uref *, int, int, uint8_t **, uint8_t);
int uref_sound_plane_read_int16_t(struct uref *, char const *, int, int, int16_t const **);
int uref_sound_plane_write_int16_t(struct uref *, char const *, int, int, int16_t **);
int uref_sound_read_int16_t(struct uref *, int, int, int16_t const **, uint8_t);
int uref_sound_write_int16_t(struct uref *, int, int, int16_t **, uint8_t);
int uref_sound_plane_read_int32_t(struct uref *, char const *, int, int, int32_t const **);
int uref_sound_plane_write_int32_t(struct uref *, char const *, int, int, int32_t **);
int uref_sound_read_int32_t(struct uref *, int, int, int32_t const **, uint8_t);
int uref_sound_write_int32_t(struct uref *, int, int, int32_t **, uint8_t);
int uref_sound_plane_read_float(struct uref *, char const *, int, int, float const **);
int uref_sound_plane_write_float(struct uref *, char const *, int, int, float **);
int uref_sound_read_float(struct uref *, int, int, float const **, uint8_t);
int uref_sound_write_float(struct uref *, int, int, float **, uint8_t);
int uref_sound_plane_read_double(struct uref *, char const *, int, int, double const **);
int uref_sound_plane_write_double(struct uref *, char const *, int, int, double **);
int uref_sound_read_double(struct uref *, int, int, double const **, uint8_t);
int uref_sound_write_double(struct uref *, int, int, double **, uint8_t);
int uref_sound_resize(struct uref *, int, int);
int uref_sound_interleave(struct uref *, uint8_t *, int, int, uint8_t, uint8_t);
int uref_sound_replace(struct uref *, struct ubuf_mgr *, int, int);
]]
libupipe = ffi.load("libupipe.so", true)
libupipe_static = ffi.load("libupipe.static.so", true)
