local ffi = require("ffi")
ffi.cdef [[
enum uprobe_ts_scte35p_event {
	UPROBE_TS_SCTE35P_SENTINEL = 32768,
	UPROBE_TS_SCTE35P_EVENT,
};
enum uprobe_ts_demux_event {
	UPROBE_TS_DEMUX_SENTINEL = 32768,
	UPROBE_TS_DEMUX_SPLIT = 36864,
};
enum uprobe_ts_split_event {
	UPROBE_TS_SPLIT_SENTINEL = 36864,
	UPROBE_TS_SPLIT_ADD_PID,
	UPROBE_TS_SPLIT_DEL_PID,
};
enum uprobe_ts_mux_event {
	UPROBE_TS_MUX_SENTINEL = 32768,
	UPROBE_TS_MUX_LAST_CC,
	UPROBE_TS_MUX_ENCAPS = 36864,
};
enum uprobe_ts_encaps_event {
	UPROBE_TS_ENCAPS_SENTINEL = 36864,
	UPROBE_TS_ENCAPS_STATUS,
};
struct upipe_mgr *upipe_ts_check_mgr_alloc(void);
struct upipe_mgr *upipe_ts_decaps_mgr_alloc(void);
struct upipe_mgr *upipe_ts_eitd_mgr_alloc(void);
struct upipe_mgr *upipe_ts_nitd_mgr_alloc(void);
struct upipe_mgr *upipe_ts_pesd_mgr_alloc(void);
struct upipe_mgr *upipe_ts_patd_mgr_alloc(void);
struct upipe_mgr *upipe_ts_pmtd_mgr_alloc(void);
struct upipe_mgr *upipe_ts_psi_join_mgr_alloc(void);
struct upipe_mgr *upipe_ts_psim_mgr_alloc(void);
struct upipe_mgr *upipe_ts_psi_split_mgr_alloc(void);
struct upipe_mgr *upipe_ts_scte35d_mgr_alloc(void);
struct upipe_mgr *upipe_ts_scte35p_mgr_alloc(void);
struct upipe_mgr *upipe_ts_sdtd_mgr_alloc(void);
struct upipe_mgr *upipe_ts_tdtd_mgr_alloc(void);
struct upipe_mgr *upipe_ts_split_mgr_alloc(void);
struct upipe_mgr *upipe_ts_sync_mgr_alloc(void);
struct upipe_mgr *upipe_ts_demux_mgr_alloc(void);
struct upipe_mgr *upipe_ts_tstd_mgr_alloc(void);
struct upipe_mgr *upipe_ts_encaps_mgr_alloc(void);
struct upipe_mgr *upipe_ts_pese_mgr_alloc(void);
struct upipe_mgr *upipe_ts_psig_mgr_alloc(void);
struct upipe_mgr *upipe_ts_sig_mgr_alloc(void);
struct upipe_mgr *upipe_ts_mux_mgr_alloc(void);
int uref_ts_flow_get_conformance(struct uref *, char const **);
int uref_ts_flow_set_conformance(struct uref *, char const *);
int uref_ts_flow_delete_conformance(struct uref *);
int uref_ts_flow_match_conformance(struct uref *, char const *);
int uref_ts_flow_cmp_conformance(struct uref *, struct uref *);
int uref_ts_flow_get_pid(struct uref *, uint64_t *);
int uref_ts_flow_set_pid(struct uref *, uint64_t);
int uref_ts_flow_delete_pid(struct uref *);
int uref_ts_flow_match_pid(struct uref *, uint64_t, uint64_t);
int uref_ts_flow_cmp_pid(struct uref *, struct uref *);
int uref_ts_flow_get_pcr_pid(struct uref *, uint64_t *);
int uref_ts_flow_set_pcr_pid(struct uref *, uint64_t);
int uref_ts_flow_delete_pcr_pid(struct uref *);
int uref_ts_flow_match_pcr_pid(struct uref *, uint64_t, uint64_t);
int uref_ts_flow_cmp_pcr_pid(struct uref *, struct uref *);
int uref_ts_flow_get_max_delay(struct uref *, uint64_t *);
int uref_ts_flow_set_max_delay(struct uref *, uint64_t);
int uref_ts_flow_delete_max_delay(struct uref *);
int uref_ts_flow_match_max_delay(struct uref *, uint64_t, uint64_t);
int uref_ts_flow_cmp_max_delay(struct uref *, struct uref *);
int uref_ts_flow_get_tb_rate(struct uref *, uint64_t *);
int uref_ts_flow_set_tb_rate(struct uref *, uint64_t);
int uref_ts_flow_delete_tb_rate(struct uref *);
int uref_ts_flow_match_tb_rate(struct uref *, uint64_t, uint64_t);
int uref_ts_flow_cmp_tb_rate(struct uref *, struct uref *);
int uref_ts_flow_get_psi_filter_internal(struct uref *, uint8_t const **, size_t *);
int uref_ts_flow_set_psi_filter_internal(struct uref *, uint8_t const *, size_t);
int uref_ts_flow_delete_psi_filter_internal(struct uref *);
int uref_ts_flow_get_psi_section_interval(struct uref *, uint64_t *);
int uref_ts_flow_set_psi_section_interval(struct uref *, uint64_t);
int uref_ts_flow_delete_psi_section_interval(struct uref *);
int uref_ts_flow_match_psi_section_interval(struct uref *, uint64_t, uint64_t);
int uref_ts_flow_cmp_psi_section_interval(struct uref *, struct uref *);
int uref_ts_flow_get_pes_id(struct uref *, uint8_t *);
int uref_ts_flow_set_pes_id(struct uref *, uint8_t);
int uref_ts_flow_delete_pes_id(struct uref *);
int uref_ts_flow_match_pes_id(struct uref *, uint8_t, uint8_t);
int uref_ts_flow_cmp_pes_id(struct uref *, struct uref *);
int uref_ts_flow_get_pes_alignment(struct uref *);
int uref_ts_flow_set_pes_alignment(struct uref *);
int uref_ts_flow_delete_pes_alignment(struct uref *);
int uref_ts_flow_cmp_pes_alignment(struct uref *, struct uref *);
int uref_ts_flow_get_pes_header(struct uref *, uint8_t *);
int uref_ts_flow_set_pes_header(struct uref *, uint8_t);
int uref_ts_flow_delete_pes_header(struct uref *);
int uref_ts_flow_match_pes_header(struct uref *, uint8_t, uint8_t);
int uref_ts_flow_cmp_pes_header(struct uref *, struct uref *);
int uref_ts_flow_get_pes_min_duration(struct uref *, uint64_t *);
int uref_ts_flow_set_pes_min_duration(struct uref *, uint64_t);
int uref_ts_flow_delete_pes_min_duration(struct uref *);
int uref_ts_flow_match_pes_min_duration(struct uref *, uint64_t, uint64_t);
int uref_ts_flow_cmp_pes_min_duration(struct uref *, struct uref *);
int uref_ts_flow_get_descriptors(struct uref *, uint64_t *);
int uref_ts_flow_set_descriptors(struct uref *, uint64_t);
int uref_ts_flow_delete_descriptors(struct uref *);
int uref_ts_flow_match_descriptors(struct uref *, uint64_t, uint64_t);
int uref_ts_flow_cmp_descriptors(struct uref *, struct uref *);
int uref_ts_flow_get_descriptor(struct uref *, uint8_t const **, size_t *, uint64_t);
int uref_ts_flow_set_descriptor(struct uref *, uint8_t const *, size_t, uint64_t);
int uref_ts_flow_delete_descriptor(struct uref *, uint64_t);
int uref_ts_flow_add_descriptor(struct uref *, uint8_t const *, size_t);
size_t uref_ts_flow_size_descriptors(struct uref *);
void uref_ts_flow_extract_descriptors(struct uref *, uint8_t *);
int uref_ts_flow_compare_descriptors(struct uref *, struct uref *);
int uref_ts_flow_get_telx_type(struct uref *, uint8_t *, uint8_t);
int uref_ts_flow_set_telx_type(struct uref *, uint8_t, uint8_t);
int uref_ts_flow_delete_telx_type(struct uref *, uint8_t);
int uref_ts_flow_match_telx_type(struct uref *, uint8_t, uint8_t, uint8_t);
int uref_ts_flow_cmp_telx_type(struct uref *, struct uref *, uint8_t);
int uref_ts_flow_get_telx_magazine(struct uref *, uint8_t *, uint8_t);
int uref_ts_flow_set_telx_magazine(struct uref *, uint8_t, uint8_t);
int uref_ts_flow_delete_telx_magazine(struct uref *, uint8_t);
int uref_ts_flow_match_telx_magazine(struct uref *, uint8_t, uint8_t, uint8_t);
int uref_ts_flow_cmp_telx_magazine(struct uref *, struct uref *, uint8_t);
int uref_ts_flow_get_telx_page(struct uref *, uint8_t *, uint8_t);
int uref_ts_flow_set_telx_page(struct uref *, uint8_t, uint8_t);
int uref_ts_flow_delete_telx_page(struct uref *, uint8_t);
int uref_ts_flow_match_telx_page(struct uref *, uint8_t, uint8_t, uint8_t);
int uref_ts_flow_cmp_telx_page(struct uref *, struct uref *, uint8_t);
int uref_ts_flow_get_sub_type(struct uref *, uint8_t *, uint8_t);
int uref_ts_flow_set_sub_type(struct uref *, uint8_t, uint8_t);
int uref_ts_flow_delete_sub_type(struct uref *, uint8_t);
int uref_ts_flow_match_sub_type(struct uref *, uint8_t, uint8_t, uint8_t);
int uref_ts_flow_cmp_sub_type(struct uref *, struct uref *, uint8_t);
int uref_ts_flow_get_sub_composition(struct uref *, uint8_t *, uint8_t);
int uref_ts_flow_set_sub_composition(struct uref *, uint8_t, uint8_t);
int uref_ts_flow_delete_sub_composition(struct uref *, uint8_t);
int uref_ts_flow_match_sub_composition(struct uref *, uint8_t, uint8_t, uint8_t);
int uref_ts_flow_cmp_sub_composition(struct uref *, struct uref *, uint8_t);
int uref_ts_flow_get_sub_ancillary(struct uref *, uint8_t *, uint8_t);
int uref_ts_flow_set_sub_ancillary(struct uref *, uint8_t, uint8_t);
int uref_ts_flow_delete_sub_ancillary(struct uref *, uint8_t);
int uref_ts_flow_match_sub_ancillary(struct uref *, uint8_t, uint8_t, uint8_t);
int uref_ts_flow_cmp_sub_ancillary(struct uref *, struct uref *, uint8_t);
int uref_ts_flow_get_tsid(struct uref *, uint64_t *);
int uref_ts_flow_set_tsid(struct uref *, uint64_t);
int uref_ts_flow_delete_tsid(struct uref *);
int uref_ts_flow_match_tsid(struct uref *, uint64_t, uint64_t);
int uref_ts_flow_cmp_tsid(struct uref *, struct uref *);
int uref_ts_flow_get_onid(struct uref *, uint64_t *);
int uref_ts_flow_set_onid(struct uref *, uint64_t);
int uref_ts_flow_delete_onid(struct uref *);
int uref_ts_flow_match_onid(struct uref *, uint64_t, uint64_t);
int uref_ts_flow_cmp_onid(struct uref *, struct uref *);
int uref_ts_flow_get_eit(struct uref *);
int uref_ts_flow_set_eit(struct uref *);
int uref_ts_flow_delete_eit(struct uref *);
int uref_ts_flow_cmp_eit(struct uref *, struct uref *);
int uref_ts_flow_get_eit_schedule(struct uref *);
int uref_ts_flow_set_eit_schedule(struct uref *);
int uref_ts_flow_delete_eit_schedule(struct uref *);
int uref_ts_flow_cmp_eit_schedule(struct uref *, struct uref *);
int uref_ts_flow_get_running_status(struct uref *, uint8_t *);
int uref_ts_flow_set_running_status(struct uref *, uint8_t);
int uref_ts_flow_delete_running_status(struct uref *);
int uref_ts_flow_match_running_status(struct uref *, uint8_t, uint8_t);
int uref_ts_flow_cmp_running_status(struct uref *, struct uref *);
int uref_ts_flow_get_scrambled(struct uref *);
int uref_ts_flow_set_scrambled(struct uref *);
int uref_ts_flow_delete_scrambled(struct uref *);
int uref_ts_flow_cmp_scrambled(struct uref *, struct uref *);
int uref_ts_flow_get_provider_name(struct uref *, char const **);
int uref_ts_flow_set_provider_name(struct uref *, char const *);
int uref_ts_flow_delete_provider_name(struct uref *);
int uref_ts_flow_match_provider_name(struct uref *, char const *);
int uref_ts_flow_cmp_provider_name(struct uref *, struct uref *);
int uref_ts_flow_get_service_type(struct uref *, uint8_t *);
int uref_ts_flow_set_service_type(struct uref *, uint8_t);
int uref_ts_flow_delete_service_type(struct uref *);
int uref_ts_flow_match_service_type(struct uref *, uint8_t, uint8_t);
int uref_ts_flow_cmp_service_type(struct uref *, struct uref *);
int uref_ts_flow_get_sdt_descriptors(struct uref *, uint64_t *);
int uref_ts_flow_set_sdt_descriptors(struct uref *, uint64_t);
int uref_ts_flow_delete_sdt_descriptors(struct uref *);
int uref_ts_flow_match_sdt_descriptors(struct uref *, uint64_t, uint64_t);
int uref_ts_flow_cmp_sdt_descriptors(struct uref *, struct uref *);
int uref_ts_flow_get_sdt_descriptor(struct uref *, uint8_t const **, size_t *, uint64_t);
int uref_ts_flow_set_sdt_descriptor(struct uref *, uint8_t const *, size_t, uint64_t);
int uref_ts_flow_delete_sdt_descriptor(struct uref *, uint64_t);
int uref_ts_flow_add_sdt_descriptor(struct uref *, uint8_t const *, size_t);
size_t uref_ts_flow_size_sdt_descriptors(struct uref *);
void uref_ts_flow_extract_sdt_descriptors(struct uref *, uint8_t *);
int uref_ts_flow_compare_sdt_descriptors(struct uref *, struct uref *);
int uref_ts_flow_get_last_table_id(struct uref *, uint8_t *);
int uref_ts_flow_set_last_table_id(struct uref *, uint8_t);
int uref_ts_flow_delete_last_table_id(struct uref *);
int uref_ts_flow_match_last_table_id(struct uref *, uint8_t, uint8_t);
int uref_ts_flow_cmp_last_table_id(struct uref *, struct uref *);
int uref_ts_flow_get_nid(struct uref *, uint64_t *);
int uref_ts_flow_set_nid(struct uref *, uint64_t);
int uref_ts_flow_delete_nid(struct uref *);
int uref_ts_flow_match_nid(struct uref *, uint64_t, uint64_t);
int uref_ts_flow_cmp_nid(struct uref *, struct uref *);
int uref_ts_flow_get_network_name(struct uref *, char const **);
int uref_ts_flow_set_network_name(struct uref *, char const *);
int uref_ts_flow_delete_network_name(struct uref *);
int uref_ts_flow_match_network_name(struct uref *, char const *);
int uref_ts_flow_cmp_network_name(struct uref *, struct uref *);
int uref_ts_flow_get_nit_descriptors(struct uref *, uint64_t *);
int uref_ts_flow_set_nit_descriptors(struct uref *, uint64_t);
int uref_ts_flow_delete_nit_descriptors(struct uref *);
int uref_ts_flow_match_nit_descriptors(struct uref *, uint64_t, uint64_t);
int uref_ts_flow_cmp_nit_descriptors(struct uref *, struct uref *);
int uref_ts_flow_get_nit_descriptor(struct uref *, uint8_t const **, size_t *, uint64_t);
int uref_ts_flow_set_nit_descriptor(struct uref *, uint8_t const *, size_t, uint64_t);
int uref_ts_flow_delete_nit_descriptor(struct uref *, uint64_t);
int uref_ts_flow_add_nit_descriptor(struct uref *, uint8_t const *, size_t);
size_t uref_ts_flow_size_nit_descriptors(struct uref *);
void uref_ts_flow_extract_nit_descriptors(struct uref *, uint8_t *);
int uref_ts_flow_compare_nit_descriptors(struct uref *, struct uref *);
int uref_ts_flow_get_nit_ts(struct uref *, uint64_t *);
int uref_ts_flow_set_nit_ts(struct uref *, uint64_t);
int uref_ts_flow_delete_nit_ts(struct uref *);
int uref_ts_flow_match_nit_ts(struct uref *, uint64_t, uint64_t);
int uref_ts_flow_cmp_nit_ts(struct uref *, struct uref *);
int uref_ts_flow_get_nit_ts_tsid(struct uref *, uint64_t *, uint64_t);
int uref_ts_flow_set_nit_ts_tsid(struct uref *, uint64_t, uint64_t);
int uref_ts_flow_delete_nit_ts_tsid(struct uref *, uint64_t);
int uref_ts_flow_match_nit_ts_tsid(struct uref *, uint8_t, uint8_t, uint64_t);
int uref_ts_flow_cmp_nit_ts_tsid(struct uref *, struct uref *, uint64_t);
int uref_ts_flow_get_nit_ts_onid(struct uref *, uint64_t *, uint64_t);
int uref_ts_flow_set_nit_ts_onid(struct uref *, uint64_t, uint64_t);
int uref_ts_flow_delete_nit_ts_onid(struct uref *, uint64_t);
int uref_ts_flow_match_nit_ts_onid(struct uref *, uint8_t, uint8_t, uint64_t);
int uref_ts_flow_cmp_nit_ts_onid(struct uref *, struct uref *, uint64_t);
int uref_ts_flow_get_nit_ts_descriptors(struct uref *, uint64_t *, uint64_t);
int uref_ts_flow_set_nit_ts_descriptors(struct uref *, uint64_t, uint64_t);
int uref_ts_flow_delete_nit_ts_descriptors(struct uref *, uint64_t);
int uref_ts_flow_match_nit_ts_descriptors(struct uref *, uint8_t, uint8_t, uint64_t);
int uref_ts_flow_cmp_nit_ts_descriptors(struct uref *, struct uref *, uint64_t);
int uref_ts_flow_get_nit_ts_descriptor(struct uref *, uint8_t const **, size_t *, uint64_t, uint64_t);
int uref_ts_flow_set_nit_ts_descriptor(struct uref *, uint8_t const *, size_t, uint64_t, uint64_t);
int uref_ts_flow_delete_nit_ts_descriptor(struct uref *, uint64_t, uint64_t);
int uref_ts_flow_add_nit_ts_descriptor(struct uref *, uint8_t const *, size_t, uint64_t);
size_t uref_ts_flow_size_nit_ts_descriptors(struct uref *, uint64_t);
void uref_ts_flow_extract_nit_ts_descriptors(struct uref *, uint8_t *, uint64_t);
int uref_ts_flow_compare_nit_ts_descriptors(struct uref *, struct uref *, uint64_t);
int uref_ts_flow_get_psi_filter(struct uref *, uint8_t const **, uint8_t const **, size_t *);
int uref_ts_flow_set_psi_filter(struct uref *, uint8_t const *, uint8_t const *, size_t);
int uref_ts_flow_delete_psi_filter(struct uref *);
enum upipe_ts_conformance {
	UPIPE_TS_CONFORMANCE_AUTO,
	UPIPE_TS_CONFORMANCE_ISO,
	UPIPE_TS_CONFORMANCE_DVB_NO_TABLES,
	UPIPE_TS_CONFORMANCE_DVB,
	UPIPE_TS_CONFORMANCE_ATSC,
	UPIPE_TS_CONFORMANCE_ISDB,
};
char const *upipe_ts_conformance_print(enum upipe_ts_conformance);
int upipe_ts_conformance_to_flow_def(struct uref *, enum upipe_ts_conformance);
enum upipe_ts_conformance upipe_ts_conformance_from_string(char const *);
enum upipe_ts_conformance upipe_ts_conformance_from_flow_def(struct uref *);
int upipe_ts_demux_get_conformance(struct upipe *, enum upipe_ts_conformance *);
int upipe_ts_demux_set_conformance(struct upipe *, enum upipe_ts_conformance);
int upipe_ts_demux_mgr_get_null_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_null_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_setrap_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_setrap_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_idem_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_idem_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_ts_split_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_ts_split_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_ts_sync_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_ts_sync_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_ts_check_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_ts_check_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_ts_decaps_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_ts_decaps_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_ts_psim_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_ts_psim_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_ts_psi_split_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_ts_psi_split_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_ts_patd_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_ts_patd_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_ts_nitd_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_ts_nitd_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_ts_sdtd_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_ts_sdtd_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_ts_tdtd_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_ts_tdtd_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_ts_pmtd_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_ts_pmtd_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_ts_eitd_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_ts_eitd_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_ts_pesd_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_ts_pesd_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_ts_scte35d_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_ts_scte35d_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_mpgaf_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_mpgaf_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_a52f_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_a52f_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_mpgvf_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_mpgvf_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_h264f_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_h264f_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_telxf_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_telxf_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_dvbsubf_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_dvbsubf_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_get_opusf_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_demux_mgr_set_opusf_mgr(struct upipe_mgr *, struct upipe_mgr *);
enum upipe_ts_mux_mode {
	UPIPE_TS_MUX_MODE_CBR,
	UPIPE_TS_MUX_MODE_CAPPED,
};
char const *upipe_ts_mux_mode_print(enum upipe_ts_mux_mode);
int upipe_ts_mux_get_conformance(struct upipe *, enum upipe_ts_conformance *);
int upipe_ts_mux_set_conformance(struct upipe *, enum upipe_ts_conformance);
int upipe_ts_mux_get_cc(struct upipe *, unsigned int *);
int upipe_ts_mux_set_cc(struct upipe *, unsigned int);
int upipe_ts_mux_set_cr_prog(struct upipe *, uint64_t);
int upipe_ts_mux_get_pat_interval(struct upipe *, uint64_t *);
int upipe_ts_mux_set_pat_interval(struct upipe *, uint64_t);
int upipe_ts_mux_get_pmt_interval(struct upipe *, uint64_t *);
int upipe_ts_mux_set_pmt_interval(struct upipe *, uint64_t);
int upipe_ts_mux_get_nit_interval(struct upipe *, uint64_t *);
int upipe_ts_mux_set_nit_interval(struct upipe *, uint64_t);
int upipe_ts_mux_get_sdt_interval(struct upipe *, uint64_t *);
int upipe_ts_mux_set_sdt_interval(struct upipe *, uint64_t);
int upipe_ts_mux_get_eit_interval(struct upipe *, uint64_t *);
int upipe_ts_mux_set_eit_interval(struct upipe *, uint64_t);
int upipe_ts_mux_get_tdt_interval(struct upipe *, uint64_t *);
int upipe_ts_mux_set_tdt_interval(struct upipe *, uint64_t);
int upipe_ts_mux_get_pcr_interval(struct upipe *, uint64_t *);
int upipe_ts_mux_set_pcr_interval(struct upipe *, uint64_t);
int upipe_ts_mux_get_max_delay(struct upipe *, uint64_t *);
int upipe_ts_mux_set_max_delay(struct upipe *, uint64_t);
int upipe_ts_mux_get_mux_delay(struct upipe *, uint64_t *);
int upipe_ts_mux_set_mux_delay(struct upipe *, uint64_t);
int upipe_ts_mux_get_octetrate(struct upipe *, uint64_t *);
int upipe_ts_mux_set_octetrate(struct upipe *, uint64_t);
int upipe_ts_mux_get_padding_octetrate(struct upipe *, uint64_t *);
int upipe_ts_mux_set_padding_octetrate(struct upipe *, uint64_t);
int upipe_ts_mux_get_mode(struct upipe *, enum upipe_ts_mux_mode *);
int upipe_ts_mux_set_mode(struct upipe *, enum upipe_ts_mux_mode);
int upipe_ts_mux_get_version(struct upipe *, unsigned int *);
int upipe_ts_mux_set_version(struct upipe *, unsigned int);
int upipe_ts_mux_freeze_psi(struct upipe *);
int upipe_ts_mux_prepare(struct upipe *, uint64_t, uint64_t);
int upipe_ts_mux_mgr_get_ts_encaps_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_mux_mgr_set_ts_encaps_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_mux_mgr_get_ts_tstd_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_mux_mgr_set_ts_tstd_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_mux_mgr_get_ts_psi_join_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_mux_mgr_set_ts_psi_join_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_mux_mgr_get_ts_psig_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_mux_mgr_set_ts_psig_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_mux_mgr_get_ts_sig_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_mux_mgr_set_ts_sig_mgr(struct upipe_mgr *, struct upipe_mgr *);
int upipe_ts_encaps_set_tb_size(struct upipe *, unsigned int);
int upipe_ts_encaps_splice(struct upipe *, uint64_t, struct ubuf **, uint64_t *);
int upipe_ts_encaps_eos(struct upipe *);
bool upipe_ts_patd_get_nit(struct upipe *, struct uref **);
bool upipe_ts_psig_program_get_pcr_pid(struct upipe *, unsigned int *);
bool upipe_ts_psig_program_set_pcr_pid(struct upipe *, unsigned int);
int upipe_ts_sig_get_nit_sub(struct upipe *, struct upipe **);
int upipe_ts_sig_get_sdt_sub(struct upipe *, struct upipe **);
int upipe_ts_sig_get_eit_sub(struct upipe *, struct upipe **);
int upipe_ts_sig_get_tdt_sub(struct upipe *, struct upipe **);
int upipe_ts_sync_get_sync(struct upipe *, int *);
int upipe_ts_sync_set_sync(struct upipe *, int);
int uref_ts_event_get_running_status(struct uref *, uint8_t *, uint64_t);
int uref_ts_event_set_running_status(struct uref *, uint8_t, uint64_t);
int uref_ts_event_delete_running_status(struct uref *, uint64_t);
int uref_ts_event_match_running_status(struct uref *, uint8_t, uint8_t, uint64_t);
int uref_ts_event_cmp_running_status(struct uref *, struct uref *, uint64_t);
int uref_ts_event_get_scrambled(struct uref *, uint64_t);
int uref_ts_event_set_scrambled(struct uref *, uint64_t);
int uref_ts_event_delete_scrambled(struct uref *, uint64_t);
int uref_ts_event_cmp_scrambled(struct uref *, struct uref *, uint64_t);
int uref_ts_event_get_descriptors(struct uref *, uint64_t *, uint64_t);
int uref_ts_event_set_descriptors(struct uref *, uint64_t, uint64_t);
int uref_ts_event_delete_descriptors(struct uref *, uint64_t);
int uref_ts_event_match_descriptors(struct uref *, uint8_t, uint8_t, uint64_t);
int uref_ts_event_cmp_descriptors(struct uref *, struct uref *, uint64_t);
int uref_ts_event_get_descriptor(struct uref *, uint8_t const **, size_t *, uint64_t, uint64_t);
int uref_ts_event_set_descriptor(struct uref *, uint8_t const *, size_t, uint64_t, uint64_t);
int uref_ts_event_delete_descriptor(struct uref *, uint64_t, uint64_t);
int uref_ts_event_add_descriptor(struct uref *, uint8_t const *, size_t, uint64_t);
size_t uref_ts_event_size_descriptors(struct uref *, uint64_t);
void uref_ts_event_extract_descriptors(struct uref *, uint8_t *, uint64_t);
int uref_ts_event_compare_descriptors(struct uref *, struct uref *, uint64_t);
int uref_ts_scte35_get_event_id(struct uref *, uint64_t *);
int uref_ts_scte35_set_event_id(struct uref *, uint64_t);
int uref_ts_scte35_delete_event_id(struct uref *);
int uref_ts_scte35_match_event_id(struct uref *, uint64_t, uint64_t);
int uref_ts_scte35_cmp_event_id(struct uref *, struct uref *);
int uref_ts_scte35_get_cancel(struct uref *);
int uref_ts_scte35_set_cancel(struct uref *);
int uref_ts_scte35_delete_cancel(struct uref *);
int uref_ts_scte35_cmp_cancel(struct uref *, struct uref *);
int uref_ts_scte35_get_out_of_network(struct uref *);
int uref_ts_scte35_set_out_of_network(struct uref *);
int uref_ts_scte35_delete_out_of_network(struct uref *);
int uref_ts_scte35_cmp_out_of_network(struct uref *, struct uref *);
int uref_ts_scte35_get_auto_return(struct uref *);
int uref_ts_scte35_set_auto_return(struct uref *);
int uref_ts_scte35_delete_auto_return(struct uref *);
int uref_ts_scte35_cmp_auto_return(struct uref *, struct uref *);
int uref_ts_scte35_get_unique_program_id(struct uref *, uint64_t *);
int uref_ts_scte35_set_unique_program_id(struct uref *, uint64_t);
int uref_ts_scte35_delete_unique_program_id(struct uref *);
int uref_ts_scte35_match_unique_program_id(struct uref *, uint64_t, uint64_t);
int uref_ts_scte35_cmp_unique_program_id(struct uref *, struct uref *);
]]
libupipe_ts = ffi.load("libupipe_ts.so.0", true)
libupipe_ts_static = ffi.load("libupipe-ts.static.so", true)
